### ISSUE TITLE
Should we provide the custom data object to replace masthead data only for our site.

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#10]
_zhumy created the following on Dec 04:_  

 Issue 1. Should we provide the custom data object to replace masthead data that only impact our site page.
As I find some commands in masthhead.js file which could custom mast head base data. Shall we used these function only change our site's masthead without change masthead.js file.
Below are the commands in masthead.js file:
                // Alias the translation file data.
		v18Data = IBM.common.translations.data.v18main;
 
		// If the custom data object exists, use that for the data.
		if (window.mhcustomtest) {
			v18Data = window.mhcustomtest;
		}

Issue 2. If masthead data can't customized,  we really like the mega-panel idea to display and describe all menu items. Would you please add the mega-panel function into menu bar, as the menu bar only support two-level menu currently. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/363_

**Comment by jeffchew** [comment]
_On Dec 06, zhaohuic commented:_
@elraymond Erica, thanks for your response to first issue - 'masthead cannot be customized' in Slack channel.

We still want to look into Issue 2 - implement mega-panel style on local menu items, would you please help to check? Thanks.

**Comment by jeffchew** [comment]
_On Dec 06, elraymond commented:_
do you have designs with this experience mocked up?

**Comment by jeffchew** [comment]
_On Dec 07, zhaohuic commented:_
Attached below is the mockup for the local menu with mega-panel style, kindly check. Thanks.
1) allow to present third level menu items in local menu
2) if hover on the second level menu item the third level menu items show in mega-panel

![image](https://media.github.ibm.com/user/12945/files/61eaa0e0-f9fd-11e8-8f3d-fbe84f142ad0)

**Comment by jeffchew** [comment]
_On Dec 07, elraymond commented:_
While that interaction shouldn't be done as it doesn't align with the journey on the rest of the site Scott Bokma, our IA expert, can help you out with some ideas for your need.

@spbokma can you share with this team some other possibilities for their L1 navigation & work with them on refining. Thanks!

**Comment by jeffchew** [comment]
_On Dec 10, zhumy commented:_
As the mockup in comment3, we have three level menu in our site. 
And we need to present related third level menu items structured and their description in local menu when user hover on the the menu items.
@spbokma  Would you please help to provide some other possibilities for the three level menu, we do not limit the presentation form, mega panel or any other form. Thanks!

**Comment by jeffchew** [comment]
_On Dec 21, spbokma commented:_
---response to email on 12/21/18
I see iyou'd like to represent and support up to 3 levels of navigation within this experience. Could you please share with me your sitemap/IA of your complete structure, as this will help me better understand your overall hierarchy and being seeing how the navigation can possibly support it. We then can begin looking at options to have a solution for you navigational needs.

**Comment by jeffchew** [comment]
_On Dec 24, zhaohuic commented:_
Thanks Scott for response.

Our application portfolio is 'Distributed Software', the applications are under ibm.com and mostly in three sets: 'passportadvantage', 'softwareandservices' and 'buyingtools'.
Five menu items in L1 menu: 'Buy now', 'My services', 'My account', 'Sales', 'Help'.

Please kindly advise. Thanks.

**Three sets of sites under ibm.com:**
//www.ibm.com/software/howtobuy/passportadvantage
//www.ibm.com/software/howtobuy/softwareandservices
//www.ibm.com/software/howtobuy/buyingtools

**Comment by jeffchew** [comment]
_On Jan 02, spbokma commented:_
Are you looking at combining the three sets into one site? If so, which pages, sections and content from the three sets are going into which of the five menu items. Do you have site map of this new IA showing which content from the three sets we are working with?

Letting you the link //www.ibm.com/software/howtobuy/buyingtools is bring up a 404 page for me.

**Comment by jeffchew** [comment]
_On Jan 03, zhaohuic commented:_
Scott, thanks for your response.

The early-phase html page is here: http://vt-mysrvs.dswcluster-test-ussouth-2.us-south.containers.appdomain.cloud/pao/paocustomer

Could you help to take a look? And kindly let's know if you need more information. Thanks.

**Comment by jeffchew** [comment]
_On Oct 17, chsanche commented:_
Note: Talked to Scott and we need to migrate this issue to our new repo for prioritization.

**Comment by ljcarot** [comment]
I would suggest closing and creating a new issue or renaming this issue so it more accurately reflects the local megamenu requirement.  Assigning to Scott for now since I think this still remains with IA.

**Comment by JennySanchez** [comment]
@ScottBokma FYI.

**Comment by ljcarot** [comment]
Ok to close this issue.
