### ISSUE TITLE
Update the Components/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#102]
> As a Cupcake website designer

> I need to: update the Component list on the Components Overview page 

> so that: our adopters can find the most up to date information about Components. 

#### Additional information

The current cupcake Component overview page can be viewed [here](https://carbon-for-ibm.netlify.com/components).

Tasks:
- [x] A paragraph on all Components detail can be viewed on the Carbon website. 
- [x] Add Footer and Masthead cards to the list.
- [x] Possibly link each one of the Component cards to its page on the Carbon website.
- [x] Add the list of the upcoming components
- [x] Add the description to the upcoming components table

#### Acceptance criteria
- [x] Content and design updated with markdowns.
- [ ] Content and design reviewed with Olivia and Wonil.

**Comment by JennySanchez** [comment]
Feedback from Wonil:
It might be a good idea to break the content into two sections - Carbon core components and IBM.com components.

**Comment by JennySanchez** [comment]
@oliviaflory Can you provide a list of the upcoming components for us to add to the page?

**Comment by oliviaflory** [comment]
Upcoming components | Description
----|----
Locale selector | Coming soon
Expressive modal | Coming soon
Horizontal rule | Coming soon
Link with icon | Coming soon
Table of contents | Coming soon
Lightbox media viewer | Coming soon

**Comment by JennySanchez** [comment]
"I will try to put together descriptions for us a little later in the week?" - Perfect.

*Question 1:* The list you have is different than the one from Wonil (see below). Which one should I make updates with?

![Screen Shot 2019-12-09 at 5 35 26 PM](https://user-images.githubusercontent.com/45213839/70482136-4e618d80-1aaa-11ea-9801-ad8a8f340486.png)


*Question 2:* The list, In general, are listed in alphabetical order. Are you ok for us to go with alphabetical order?

**Comment by oliviaflory** [comment]
@JennySanchez 
> Question 1: The list you have is different than the one from Wonil (see below). Which one should I make updates with?

I'd like to go with my list, there are a few like "embeddable image" that we don't know _enough_ about what it is to write a description / don't know if that's what we will really name the component.

Masthead (L0) and footer are already available so they don't belong in that list either.

The Masthead (L1) is behind a feature flag and also not available yet, though we might address that on the Masthead page vs this list.


>Question 2: The list, In general, are listed in alphabetical order. Are you ok for us to go with alphabetical order?

Alphabetical is ok, the list I wrote was almost in order of which ones were closer to being available. But I think alphabetical is ok too!

**Comment by JennySanchez** [comment]
@oliviaflory Perfect! I will make the update on live page asap.

**Comment by oliviaflory** [comment]
We need to update the Masthead card image to remove the blue CTA button.
<img width="354" alt="Screen Shot 2019-12-12 at 4 22 05 PM" src="https://user-images.githubusercontent.com/45692622/70750129-c96db280-1cfb-11ea-8ac1-7ce06cc97c99.png">

Carbon shows the icons in the UI shell image
<img width="305" alt="Screen Shot 2019-12-12 at 4 30 01 PM" src="https://user-images.githubusercontent.com/45692622/70750599-b27b9000-1cfc-11ea-86b7-11267f9d331f.png">



We could look at these options:
-  My IBM and Search icons
- square skeleton state for icons
- no icons
<img width="1039" alt="Screen Shot 2019-12-12 at 4 40 28 PM" src="https://user-images.githubusercontent.com/45692622/70751357-34b88400-1cfe-11ea-9b43-2620bdac3487.png">

I personally prefer the square skeletons or no icons, the real icons felt a little too distracting. What do you think @JennySanchez @jacobottesen-dgc ?

---

A general question for you both, looks like we are using a different type style for the component cart titles than what Carbon uses on their site. If it's intentional, great! Just wanted to point it out if you hadn't intended for them to be different.

<img width="545" alt="Screen Shot 2019-12-12 at 4 38 31 PM" src="https://user-images.githubusercontent.com/45692622/70751406-54e84300-1cfe-11ea-9113-1fe2f02370af.png">

**Comment by JennySanchez** [comment]
@oliviaflory @jacobottesen-dgc 

- [ ]  Yes, We need to update the Masthead card image to remove the blue CTA button.

<img width="354" alt="Screen Shot 2019-12-12 at 4 22 05 PM" src="https://user-images.githubusercontent.com/45692622/70750129-c96db280-1cfb-11ea-8ac1-7ce06cc97c99.png">

- [ ] For Mastehead, let's go with the image in the middle (square skeleton state for icons option) since it matches what we have on the Masthead page the best. 

![Screen Shot 2019-12-12 at 4 02 05 PM](https://user-images.githubusercontent.com/45213839/70752722-cc1ad880-1cf8-11ea-8d9f-144dccf3706c.png)


- [ ] Yes, we need to update the type style to match what Carbon has.

<img width="545" alt="Screen Shot 2019-12-12 at 4 38 31 PM" src="https://user-images.githubusercontent.com/45692622/70751406-54e84300-1cfe-11ea-9113-1fe2f02370af.png">

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Link to the "Upcoming components" description: https://ibm.ent.box.com/notes/573320778659

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Mike mentioned the images for the Footer and Masthead cards need refinement. I agreed with him, so can you attach the image work file here and I will update the image on Monday? Just wanna add the comment here so I won't forget.

![Screen Shot 2019-12-12 at 6 08 09 PM](https://user-images.githubusercontent.com/45213839/70759108-d2b24b80-1d0a-11ea-86f3-0cad56fc2ade.png)

**Comment by jacobottesen-dgc** [comment]
I updated the Component overview page with the new component descriptions from Olivia. I also updated the image for the masthead. I fixed the text size on the image cards but now the text is at the bottom of the card. 

Live link: https://deploy-preview-196--carbon-for-ibmdotcom.netlify.com/components/

![Screen Shot 2019-12-13 at 3.02.04 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/f686632d-8519-4783-8b4b-8d6ebc6d0b4b)

**Comment by JennySanchez** [comment]
@mjabbink Below are the updated images for the Footer and Masthead, please let me know what do you think. 

![Screen Shot 2019-12-16 at 6 26 27 PM](https://user-images.githubusercontent.com/45213839/70954151-9ac04680-2031-11ea-9f81-0015a172c443.png)

**Comment by mjabbink** [comment]
yes.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Let's update the images.
![Screen Shot 2019-12-17 at 2 05 57 PM](https://user-images.githubusercontent.com/45213839/71030252-b7628a00-20d6-11ea-8aa4-3b537f5eed37.png)
[Updated footer and masthead images.sketch.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/3975241/Updated.footer.and.masthead.images.sketch.zip)

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Images have been updated. Live link: https://ibm-dotcom-library.netlify.com/components/

**Comment by JennySanchez** [comment]
https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/63
