### ISSUE TITLE
Cupcake website content QA - Get started and Components section 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#108]
> As a cupcake website content creator

> I need the stream lead to review the website content to make sure there are no errors on the website content

> So that I can provide the adopter the correct information when they visit the website.

#### Additional information
- The Cupcake website can be reviewed [here](https://carbon-for-ibm.netlify.com/).
- The Cupcake website QA will focus on content accuracy. 
- All visual and feature enhancement will be listed for the Cupcake v1.1 release.

#### Acceptance criteria
- [x] A list of the QA items created for Jacob and Jenny to work on in markdowns if needed.

**Comment by oliviaflory** [comment]
### Footer
**Types**

Name | Description
------------ | -------------
Default | Default footer variant includes high-level corporate links that can vary by geographical location and may change periodically. Default footer is automatically generated based on the country and language code that you set on your page in the metadata. The Default footer is recommended for all IBM.com pages.
Minimal | Minimal footer variant removes the additional IBM navigation, this should be used in transactional experiences where the user is trying to complete a specific task, like registering for an IBM account.

☝️ We want people to use the default footer, so I removed the copy about default "taking up more space" and minimal "used when screen real-estate is limited"

---

Does anyone know how the footer content is generated? Curious if it is the same as v18, or if we need to do anything to auto generate like stated below:
- Default footer is automatically generated based on the country and language code that you set on your page in the metadata.
- Use the Template Generator or a content management tool to generate the footer HTML with the proper country and language links.

☝️ are these two statements conflicting? Do you *need* a template generator if the content is auto generated??

**Comment by JennySanchez** [comment]
@ScottBokma Can you assist Olivia with her questions?

**Comment by ScottBokma** [comment]
@oliviaflory The current IBM footer content is coming from the IBM homepage and that team would know best for any questions you have about the footer. Peter Barros leads that team and is my main contact when I have questions about the IBM nav, homepage and footer.

**Comment by oliviaflory** [comment]
@wonilsuhibm you asked me to yell at you :) 

Need to work out the footer generation and descriptions for default and minimal footer.

**Comment by JennySanchez** [comment]
@oliviaflory @wonilsuhibm Besides of the footer generation and descriptions for default and minimal footer. Please start the reviewing process and making the QA list. Thank you.

**Comment by oliviaflory** [comment]
@wonilsuhibm I propose that we remove the descriptions of how the footer is generated for the initial release, and create a story for one of the developers to write content for that within the v1.1 website release cycle. We're too close to publishing date to ask the devs to pause any of the work they have scheduled for this sprint.

Proposed footer content re-write:

Name | Description
------------ | -------------
Default | The default footer includes high-level corporate links that can vary by geographical location and may change periodically. The Default footer is recommended for all IBM.com pages.
Minimal | The minimal footer removes all high-level corporate navigation, leaving the required legal links, locale selector and branding. The minimal footer is reserved for approved adopters only and is not recommended for general use on IBM.com
Minimal | *Alternate* The minimal footer removes all high-level corporate navigation. The minimal footer is not recommended for all IBM pages and should only be used by approved adopters.

**Additionally the minimal or short footer is not available in our storybook, I don't see it in our experimental story book either. Should we hide it for this initial release since it is not available??**

**Comment by oliviaflory** [comment]
My QA comments for Overview and Masthead page:

### Overview

- [ ] Update "Carbon for IBM.com" to "IBM.com Library"

<img width="618" alt="Screen Shot 2019-12-17 at 4 12 09 PM" src="https://user-images.githubusercontent.com/45692622/71035129-d5d18100-20e8-11ea-8e82-0ab617f5c461.png">

---

- [ ] Update to "IBM.com Library components"
<img width="491" alt="Screen Shot 2019-12-17 at 4 12 58 PM" src="https://user-images.githubusercontent.com/45692622/71035238-087b7980-20e9-11ea-9298-22072d8fffb9.png">

---

### Masthead

- [ ] I think these should be in a list, the * looks incorrect
<img width="860" alt="Screen Shot 2019-12-17 at 4 15 22 PM" src="https://user-images.githubusercontent.com/45692622/71035339-3b257200-20e9-11ea-9318-b25fb3ad59f2.png">

---

Still waiting on feedback from Wonil about my Footer feedback in the comment above ☝️

**Comment by wonilsuhibm** [comment]
# Footer

### Intro copy suggestion

#### Before
`The footer is a required navigational element that displays consistently at the bottom of each page of IBM.com. `

#### After
`The footer is a section that sites at the bottom of any IBM.com page, and acts as the catch–all section that helps users navigate, provides corporate level general and legal informations. The footer is required on all pages on IBM.com.`

`There are two different footer. All pages are required to use the default footer, with the exception of a few pages that need to minimize distraction, such as checkout process. Please contact us if you think your page needs approval to use the minimal footer.`

### Content order suggestion
The current content structure doesn't make much sense to me. I completely understand that we are following Carbon template, but the current structure where the description of the two versions is separate from the visuals is really throwing me off, and is a bad user experience.

Here is what I suggest.

1. Intro copy
2. Default footer
   - Title: `Default footer`
   - Description: `
   - Visual
   - Anatomy
3. Minimal footer
   - Title: `Minimal footer`
   - Description
   - Visual
4. Rules

**Comment by JennySanchez** [comment]
Based on the discussion we had, we will update the intro copy for the release tomorrow and look at the content order structure post-release (issue created - #229)

**Comment by JennySanchez** [comment]
Update completed and all other Dev. related fix are recorded in the dev fix issue #63.
