### ISSUE TITLE
Line length guidelines

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#11]
_Wonil-Suh1 created the following on Jan 28:_  

 ## User story
As a a designer I need guidelines around line lengths and text element size so that I can design consistent experiences.

## Deliverables
- [ ] finalize line length guidelines (explorations have been done) in Sketch

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/495_

**Comment by jeffchew** [comment]
_On Jan 29, Wonil-Suh1 commented:_
The line length exploration from Duo is [here](https://ibm.box.com/s/d5djb8cmwkz4m95h89ys49ztqmtqbs9w).

**Comment by jeffchew** [comment]
_On Feb 17, chsanche commented:_
@Wonil-Suh1 This is awesome. While it's not directly linked, I'd like you to also be aware of the #473. In a high-level, I created the issue bc I noticed many of the CTA labels are long and misleading across the IBM.com and even on our website.

**Comment by jeffchew** [comment]
_On Apr 12, chsanche commented:_
@Wonil-Suh1 We should get Collen or Jill involved in this task.

**Comment by jeffchew** [comment]
_On Jul 22, chsanche commented:_
@Wonil-Suh1  Which version of the website is this task for? Thank you.

**Comment by jeffchew** [comment]
_On Jul 22, Wonil-Suh1 commented:_
@chsanche No new contents except comms related will be added to the current site. So this would be for the wedding cake.

**Comment by jeffchew** [comment]
_On Oct 17, chsanche commented:_
Note: @Jeff-Chew we need to migrate this issue to our new repo for prioritization.

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available.  The design kit and components will continue.

**Comment by RobertaJHahn** [comment]
The guidelines work has been deferred until resources are available. The design kit and components will continue.
