### ISSUE TITLE
Cupcake website content QA - Get started and Layout Patterns section 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#110]
> As a cupcake website content creator

> I need the stream lead to review the website content to make sure there are no errors on the website content

> So that I can provide the adopter the correct information when they visit the website.

#### Additional information
- The Cupcake website can be reviewed [here](https://carbon-for-ibm.netlify.com/).
- The Cupcake website QA will focus on content accuracy. 
- All visual and feature enhancement will be listed for the Cupcake v1.1 release.

#### Acceptance criteria
- [ ] A list of the QA items created for Jacob and Jenny to work on in markdowns if needed.

**Comment by JennySanchez** [comment]
@ScottBokma @larahanlon2 @wonilsuhibm Please start the reviewing process and making the QA list. Thank you.

**Comment by larahanlon2** [comment]
Hey @JennySanchez will all the `Carbon for IBM.com` titles/labels/mentions across the site need to change now that we are moving forward with `IBM.com Library`? https://ibm-dotcom-library.netlify.com/getting-started

**Comment by JennySanchez** [comment]
Yes, it's on the QA list and the content update is completed.
This task is completed. All other Dev. related fix are recorded in the dev fix issue #63.
