### ISSUE TITLE
[Search with typeahead] missing component page and documentation

### ISSUE THREAD

**Issue by kennylam** [carbon-design-system/ibm-dotcom-library-website#1162]
The [`Search with typeahead`](https://www.ibm.com/standards/carbon/web-components/?path=/story/components-search-with-typeahead--default) is missing a content/docs page in the components section of the website.

## Task

Create a component page for `search with typeahead`.

**Comment by shixiedesign** [comment]
There are a few issues with the page and the component's storybook entry. The component is more like a "sub-component", better to be mentioned in the masthead page & lead space search page.
