### ISSUE TITLE
Discussion needed - Usage of icon on left nav

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#12]
_chsanche created the following on Jan 30:_  

 ## User story

As a designer,  I need to know if I can use icons for the left nav so that I can design and follow the guideline properly.

## Deliverables

- A unified decision on if we are going to have the icon usage included in our nav guideline.

### Notes

- We tend to see the treatment for the product team and for software UI.
- My IBM team is using icons in the nav.
![screen shot 2019-01-30 at 1 50 17 pm](https://media.github.ibm.com/user/5181/files/ab091c56-24b0-11e9-9677-d7ac8f6999ee)

### Tasks

- [ ] have a discussion about it
If we are going to include it then we need to create a separate issue to create usage guidelines and shell for it. 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/507_

**Comment by jeffchew** [comment]
_On May 23, chsanche commented:_
@spbokma and @larahanlon FYI on this task issue existed.

**Comment by jeffchew** [comment]
_On Oct 17, chsanche commented:_
Note: @Jeff-Chew  we need to migrate this issue to our new repo for prioritization.

**Comment by wonilsuhibm** [comment]
@JennySanchez The Carbon UI Shell left panel component lists styling around this use case. For productive experiences such as My IBM, Search, I think it makes sense to allow this and follow Carbon styling.

We should keep this issue though — I think we will need separate guidelines for dot com makers especially around UI Shell VS layout component usage.

**Comment by JennySanchez** [comment]
Agreed, @wonilsuhibm .
