### ISSUE TITLE
Add analytics tags to the cupcake website

### ISSUE THREAD

**Issue by RobertaJHahn** [carbon-design-system/ibm-dotcom-library-website#120]
#### User Story

> As a `[user role below]`:
As a designer for the design system site

> I need to:
measure traffic and engagement on the Carbon for ibm.com web site

> so that I can:
report on and plan for the traffic to manage performance

#### Additional information

 - Original Digital Design repo [issue #233](https://zenhub.ibm.com/app/workspaces/digital-design-system-5b3a815a8bf6a932efa6fd03/issues/webstandards/northstar-website-external/233)
 - Discussion detail can be viewed via issue [409](https://github.ibm.com/webstandards/digital-design/issues/409)

#### Acceptance criteria
 - [ ]  Traffic and engagement reports are available

**Comment by JennySanchez** [comment]
@RobertaJHahn I think this is the same task as #21? What do you think?

**Comment by JennySanchez** [comment]
@RobertaJHahn NM. This task is about **enabled Segment on the design system site** and will be a dev task. 

FYI - @jeffchew

**Comment by RobertaJHahn** [comment]
Linda will be adding the cupcake website to the digital registry.  Analytics will be provided automatically.  Closing this issue
