### ISSUE TITLE
Add metadata and DDO content cards to the Resources page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#128]
> As a Cupcake website creator,

> I need to add a card on the Resource page for metadata and DDO content 

> So that our adopter knows where to find the information.

#### Additional information

(based on the discussion via #113)

- @jeffchew  will create documents for metadata or DDO on our repo [DOC folder](https://github.com/carbon-design-system/ibm-dotcom-library/tree/master/docs). Once it's done, Jeff will provide the URL for linking.

- We will add a section under Development resources on the [Resources page](https://carbon-for-ibmdotcom.netlify.com/resources) with a card for linking. Jeff will guide what we should have for the section title.

#### Acceptance criteria
- [ ] The card for metadata and DDO content is added to the Resource page with markdowns and published.

**Comment by JennySanchez** [comment]
Hi @jeffchew 
Any update on creating the metadata and DDO documents on our repo DOC folder? 
Do you have a dev issue created for me to add as a dependency?

**Comment by jeffchew** [comment]
@JennySanchez @jacobottesen-dgc documentation has been added to the IBM.com Library repo: https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/docs/building-for-ibm-dotcom.md

**Comment by JennySanchez** [comment]
@jeffchew Thank you.

**Comment by JennySanchez** [comment]
Resource page updated and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/resources/).

**Comment by jeffchew** [comment]
> Resource page updated and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/resources/).

It's going to the docs folder, but the `building for ibm.com` page should go here:
https://github.com/carbon-design-system/ibm-dotcom-library/blob/master/docs/building-for-ibm-dotcom.md
