### ISSUE TITLE
Create and publish "Cloud product page patterns" on the wedding cake website

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#13]
_Wonil-Suh1 created the following on Feb 04:_  

 ## User story

As a designer I need to be able to use the Cloud product page layouts and bands while designing so that I can align my pages to the standards.

## Deliverables

- Sketch library
- Publish on the design system site
 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/524_

**Comment by jeffchew** [comment]
_On Oct 17, chsanche commented:_
Note: @Jeff-Chew we need to migrate this issue to our new repo for prioritization.

**Comment by RobertaJHahn** [comment]
Pattern pages are still needed on the wedding cake site.  Work not scheduled yet as Carbon strategy interlock was needed.

**Comment by RobertaJHahn** [comment]
Pattern pages are still needed on the wedding cake site. Work not scheduled yet as Carbon strategy interlock is needed.
