### ISSUE TITLE
Create and update the Lead space page/Patterns in use section images

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#165]
> As a IBM.com Library website creator, 

> I need to create the Patterns in use section images to be displayed as a gallery layout with mockup style images,

> so that it looks more refined.

#### Additional information

- The v1.0 Lead space page can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/patterns/leadspace).

- Below are the examples of the Gallery style images provided by @larahanlon2 for references.![Screen Shot 2019-12-09 at 3.32.50 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/1e3f832d-0702-48b5-8928-ab69c4ad12d3)
![Screen Shot 2019-12-09 at 5.13.22 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/eb2f8127-6dbb-4075-b288-b5f4ba53b9ad)

#### Acceptance criteria
- [x] Images created in Sketch app.

**Comment by JennySanchez** [comment]
@larahanlon2 Are there any good examples/screens from the teams that Jacob and I can use to create the images for the update?

**Comment by larahanlon2** [comment]
Hey, @JennySanchez @jacobottesen-dgc the screenshots I used on the current guideline page were the best examples I could find – that align to our design specs. Here they are:

[Watson](https://ibm.box.com/s/15vajrvcptj9btor430wa03242lfazeh)
[Cloud](https://ibm.box.com/s/e1a2e8kcrjfv0oalmcrmohsgy2inkpro)
[Watson (2)](https://ibm.box.com/s/9vahduoh4sbkbxzqvgz82a7vecs983xs)
[Watson (3)](https://ibm.box.com/s/xt4pv9mg4ta650ixr6s87s01veal6yzl)
[Learn page lead space – centered](https://ibm.box.com/s/kjd7aydousmynd3retug3h9q0vg9fx7k)

**Comment by JennySanchez** [comment]
Based on the conversation I had with Lara. We need to update the Lead space page content before dive into the image update. This task will be placed in the backlog.

FYI - @RobertaJHahn

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Based on our conversation, you need to focus on higher priority tasks and will not be available to continue this task next sprint. 

Task issue #376 is created for me to pick up the task and continue the work in Sprint 20-07. Can you share the link to your Sketch work file here?

**Comment by jacobottesen-dgc** [comment]
@JennySanchez 

Here is a box link to the sketch file: https://ibm.box.com/s/rbzpflvn926gqpw2mzinjr53j2jf79wa

Let me know if you have any questions about the file!
