### ISSUE TITLE
Update the Components/Overview Page (card title type styling)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#191]
As a Carbon for IBM.com website creator

I need to present the components in the same set up on the overview page

So that our website page looks at its best with consistency.

#### Additional information
- The Components Overview page can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/components).
- We need to update the type style to match what Carbon has.
![Screen Shot 2019-12-12 at 4.51.08 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f2d97f9f-3979-4f27-abe3-1305d0ee1273)
- The horizontal spacing between the cards need adjustment as well.

 👉 **FYI:** we are updating the images on the cards.

#### Acceptance criteria
- [x] Type style on the cards for Footer and Masthead are updated on the live website and match what Carbon has.
- [ ] horizontal spacing between the cards are updated on the live website and match what Carbon has.

**Comment by JennySanchez** [comment]
@jeffchew Please add the story point to this issue when you started.
@RobertaJHahn FYI.

**Comment by mjabbink** [comment]
Also the thin divider rule between cards should be grey 20.

**Comment by mjabbink** [comment]
https://gatsby-theme-carbon.now.sh/components/ResourceCard#example

**Comment by mjabbink** [comment]
@JennySanchez 
— Your illustration for Masthead should reflect the two heights for L0 and L1.

— Footer 8-bar shape should reflect proportion of 8-bar and headers over lists are just bolder not larger type and no extra spacing under them.

:wink:

**Comment by JennySanchez** [comment]
@mjabbink I do not and will reach out to her.

**Comment by JennySanchez** [comment]
@jeffchew  For the [Components/Overview page](https://carbon-for-ibmdotcom.netlify.com/components) Jacob and I tried to make the card title work but the `font styling`, `title location`, and `horizontal spacing between cards` still not correctly displayed. This is the latest we have:
![Screen Shot 2019-12-16 at 2 39 40 PM](https://user-images.githubusercontent.com/45213839/70941389-f084f680-2011-11ea-9970-de3546282350.png)

---

I am not sure if this is a universal fix, but on the [Homepage](https://carbon-for-ibmdotcom.netlify.com/) (still WIP), we are having an issue for the horizontal spacing set up with the cards as well.

![Screen Shot 2019-12-16 at 2 47 19 PM](https://user-images.githubusercontent.com/45213839/70941868-ffb87400-2012-11ea-8d19-53caa8565733.png)

**Comment by jeffchew** [comment]
> @jeffchew For the [Components/Overview page](https://carbon-for-ibmdotcom.netlify.com/components) Jacob and I tried to make the card title work but the `font styling`, `title location`, and `horizontal spacing between cards` still not correctly displayed. This is the latest we have:
> ![Screen Shot 2019-12-16 at 2 39 40 PM](https://user-images.githubusercontent.com/45213839/70941389-f084f680-2011-11ea-9970-de3546282350.png)
> 
> I am not sure if this is a universal fix, but on the [Homepage](https://carbon-for-ibmdotcom.netlify.com/) (still WIP), we are having an issue for the horizontal spacing set up with the cards as well.
> 
> ![Screen Shot 2019-12-16 at 2 47 19 PM](https://user-images.githubusercontent.com/45213839/70941868-ffb87400-2012-11ea-8d19-53caa8565733.png)

We might have to override styling of the Gatsby theme to make this look right.

**Comment by jeffchew** [comment]
> > @jeffchew For the [Components/Overview page](https://carbon-for-ibmdotcom.netlify.com/components) Jacob and I tried to make the card title work but the `font styling`, `title location`, and `horizontal spacing between cards` still not correctly displayed. This is the latest we have:
> > I am not sure if this is a universal fix, but on the [Homepage](https://carbon-for-ibmdotcom.netlify.com/) (still WIP), we are having an issue for the horizontal spacing set up with the cards as well.
> 
> We might have to override styling of the Gatsby theme to make this look right.

Fixed and pushed up to master.

**Comment by JennySanchez** [comment]
@jeffchew I looked again and I think the card title is in IBM Plex Mono?

Our current set up:
![Screen Shot 2019-12-19 at 3 47 59 PM](https://user-images.githubusercontent.com/45213839/71212763-92594d00-2277-11ea-94fe-8b171ca3d95a.png)

Carbon set up:
View live page [here](https://www.carbondesignsystem.com/components/overview)
![Screen Shot 2019-12-19 at 3 48 15 PM](https://user-images.githubusercontent.com/45213839/71212750-8cfc0280-2277-11ea-921e-811d28df737f.png)

**Comment by mjabbink** [comment]
Those images for footer and masthead are incorrect 

Also no need to override. What you’re trying to do is very doable in Gatsby theme

**Comment by jeffchew** [comment]
> Those images for footer and masthead are incorrect
> 
> Also no need to override. What you’re trying to do is very doable in Gatsby theme

Hi @mjabbink ,

while it's very doable for regular pages with the `.container` class, it seems to not apply for the homepage specifically, since the row/column classes for the small gutter columns are targeted for `.container` and not `.container--homepage`, which is what is happening here. I had to write some override classes to apply to the homepage as well, but might be something we would want to contribute back to the gatsby theme repo.

**Comment by mjabbink** [comment]
@jeffchew and @JennySanchez Not sure I follow? Is the Carbon homepage not Gatsby? Does it have overrides?

**Comment by mjabbink** [comment]
the article cards are spaced too far apart in current staging site.
https://gatsby-theme-carbon.now.sh/components/ArticleCard

**Comment by mjabbink** [comment]
This looks odds Feature card component has the issue of the card not bleeding on the right side. The latest version of Gatsby resoled this exact issue so do you need to update or is this a bug?



<img width="531" alt="Screen Shot 2019-12-20 at 5 30 40 PM" src="https://user-images.githubusercontent.com/32881239/71298793-6a3d1d00-234f-11ea-9ee9-a3dd46df2cea.png">

**Comment by mjabbink** [comment]
@JennySanchez I recommend not scaling the Color block image in mobile and using a image made for mobile made up of 9 squares. 



Something like this:

<img width="363" alt="Screen Shot 2019-12-20 at 5 43 08 PM" src="https://user-images.githubusercontent.com/32881239/71298956-3e6e6700-2350-11ea-8d12-412f46e525e4.png">

**Comment by mjabbink** [comment]
Also the "switcher" component (top right) should be modified. The future sites of Journey Systems and Accessibility will we added later. 


<img width="286" alt="Screen Shot 2019-12-20 at 6 09 59 PM" src="https://user-images.githubusercontent.com/32881239/71299630-f6514380-2353-11ea-90e0-be3ccbdc050d.png">

**Comment by mjabbink** [comment]
also the link in bottom of left nav to carbon site defies the logic of the switcher which has all the IBM Design eco system sites. Why is this pulled out? It should link to Carbon Design kit.

<img width="305" alt="Screen Shot 2019-12-20 at 6 27 16 PM" src="https://user-images.githubusercontent.com/32881239/71299976-a32cc000-2356-11ea-9204-f684052610a9.png">

**Comment by alisonjoseph** [comment]
@jeffchew we updated the theme so that the homepage should now include the `container` class, which should fix the spacing of the cards. Are you on the latest version?

**Comment by JennySanchez** [comment]
@mjabbink  For the link in the bottom of the left nav, our thinking is if our adopter needs a quick switch to go to the Carbon website site to learn more about the Carbon, they will be able to do so on the left nav. Since the IBM.com library is built based on the Carbon Design System. Also, not all of our adopters are designers or need the Carbon design kit so linking to the design kit might not be the best.

**Comment by JennySanchez** [comment]
@jeffchew I consolidated all the Homepage dev fixes to #245 - FYI.

**Comment by mjabbink** [comment]
@JennySanchez no need to explain such a concept and thats what the switcher is for that I poster above. If you want to link to Carbon do it in logical places in the page or let the the switcher be the functionality for traversing websites.

**Comment by mjabbink** [comment]
Before you go changing constructs and concepts in place for a year please let’s discuss before implementing

**Comment by mjabbink** [comment]
Also just noticed this giant card on the lead space image.

<img width="1526" alt="Screen Shot 2019-12-23 at 3 46 27 PM" src="https://user-images.githubusercontent.com/32881239/71381956-7e755a00-259b-11ea-858c-2d4c2c1835d2.png">

**Comment by mjabbink** [comment]
@JennySanchez Does not to be Design kit but mainly not linking to the Carbon site. If that is the case why not have IDL, Brand Center sites also?

**Comment by mjabbink** [comment]
@JennySanchez @wonilsuhibm The switcher should not be getting modified. This is a shared global element with naming and taxonomy being approved Phil Gilbert. That switcher represents IBM Design. If you guys have issues with the names and such let us know and we can discuss and make any necessary changes. Eunice Chung has been working this and it}s connected to the new w3 IBM Design site (staging here: http://w3-design-site-staging.w3ibm.mybluemix.net/design/resources/practices)

**Comment by wonilsuhibm** [comment]
@mjabbink Agreed that the app switcher should not change.

@JennySanchez do you have a place where you are collecting all of the feedbacks?

**Comment by wonilsuhibm** [comment]
Also noticed that the home page lead space is a card, instead of the just that `Getting started` card. And the `Getting started` card seems a bit too large — it should be the same size as other cards on the page.

**Comment by jeffchew** [comment]
@wonilsuhibm @JennySanchez the homepage leadspace is actually using the featurecard, and don't think it was originally designed for that space. I'll take a look to see if adjustments to the styles can be made to accommodate.

**Comment by jeffchew** [comment]
> @jeffchew I consolidated all the Homepage dev fixes to #245 - FYI.
> 
> PS: Please make sure we have the latest Gatsby Theme installed before you or any dev. start on the tasks.

Hi @JennySanchez @alisonjoseph we are on `v1.18.0`. I'll pull down latest.

**Comment by JennySanchez** [comment]
@wonilsuhibm The task issue #246 is the issue created to track general feedback and fixes.

**Comment by JennySanchez** [comment]
@mjabbink Just got back from the vacation. I got what you saying and agreed with you on the switcher should not be changed if it is a shared global element across all the design sites, that was a piece of information I had no idea about but learned. 

We should have the Carbon website link removed and make sure it's going to the digital design kit instead.
