### ISSUE TITLE
Cupcake website traffic tracking planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#21]
We need to track the NPS (Net Promoter Score) as a metric to measure our growth and outcome. (Hotjr is what we are currently using to track the v19a website) 

We should look into other tools that can not only track the NPS score but also the following areas:
- Traffic, so we know how many adopters visited our website.  We need to differentiate the new visitors from the return visitors.
- Heatmaps, so we can see where our adopters click the most on a particular page and spot the opportunities for improvements.
- Adopter research, so we can see how our adopter's journeys are navigating through the Cupcake website, and spot the adopter pain points or opportunities for improvements.

**Additional context** 
Wonil mentioned Ashley Graham knows how to set up the NPS tracing in Hotjar.

#### Acceptance criteria
- [x] Have a clear next step for the development team to set the tracking up.

**Comment by JennySanchez** [comment]
@wonilsuhibm @jeffchew @photodow FYI.

**Comment by RobertaJHahn** [comment]
@JennySanchez I have removed this issue from the v1.0.0 release based on your response to my email.  What release should it be included in?

**Comment by JennySanchez** [comment]
@RobertaJHahn The release is for "Cupcake v1.0.0." and the epic is the "Website: cupcake MVP".

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you set up something for us and Ashley to chat soon? Thanks.

**Comment by JennySanchez** [comment]
FYI - @RobertaJHahn  @jacobottesen-dgc 

I am taking Jeff off this task, bc we need to find out what we need to set the process up then create a dev issue for Jeff and his team for dev assistance if we need to.

**Comment by jacobottesen-dgc** [comment]
Meeting set up with Penny for Thursday 9th 

cc. @JennySanchez

**Comment by ljcarot** [comment]
Need a dev story to add Tealium script to the cupcake website pages.  @jeffchew   https://ibm-dotcom-library.mybluemix.net/

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew Do you need me create a dev issue for adding Tealium script? Anything else I should add as the next step?

**Comment by JennySanchez** [comment]
**FYI:** Form the conversation Jacob and I had with Penny, she also recommended using the Hotjar survey to collect feedback in the long run. We have an issue to work on the survey detail in the next sprint.

**Comment by JennySanchez** [comment]
Issue #279 is created by Linda to add Tealium script to Cupcake website pages as the next step.
