### ISSUE TITLE
Study and update the "tag" label text and styling

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#227]
> As a cupcake website content creator

> I need to update our tag label and styling to match what Carbon has

> So that I can make sure our website content is 100% aligned with the Carbon website.

#### Additional information
- The tag keys information can be viewed on the Carbon website [here](https://www.carbondesignsystem.com/components/component-status).

![Screen Shot 2019-12-19 at 12.33.30 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/b45dce8e-2af9-40b2-9d08-995dea40b2db)

#### Acceptance criteria
- [ ] All tag labels are updated and live on the website.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc FYI.

**Comment by jacobottesen-dgc** [comment]
This is task is done. Changes can be viewed here: https://ibm-dotcom-library.netlify.com/components

**Comment by JennySanchez** [comment]
@jacobottesen-dgc The updates look good. I have Lara and Olivia confirm the updates as well 0 FYI.

**Comment by JennySanchez** [comment]
@larahanlon2 @oliviaflory I know there are some status updates we need to do for the Components and Layout Patterns Overview pages and you are both working on the detail. 

Let's do the status update and other content updates in a separate issue for v1.1 release and close this task for this sprint since this one is about the tag styling update to be aligned with the style the Carbon website is using.
