### ISSUE TITLE
Make sure the "Token label" can be displayed in one line

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#234]
> As a cupcake website content creator

> I need to make sure the Token label is displayed in one line,

> So that our adopters can see the Token label correctly.

#### Additional information
- [ ] Status labels and Token labels work will be done via issue #227

![Screen Shot 2019-12-19 at 4.52.05 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/73b2a891-68eb-470d-badc-2e1e6f36a64c)

#### Acceptance criteria
- [ ] Token label can be displayed in one line on the live website.

**Comment by JennySanchez** [comment]
@jeffchew I am not sure if you or Anna worked on this fix already?

**Comment by jeffchew** [comment]
This has already been completed @JennySanchez .

cc: @jacobottesen-dgc @RobertaJHahn
