### ISSUE TITLE
Cupcake website page content update - Layout Pattern/Overview page

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library-website#244]
Added a new Box note with the content suggestion for the layout page [here](https://ibm.box.com/s/brloq2aq09342zgbfbx9w78d15nu5ahc).

And the Sketch file for the assets are [here](https://ibm.box.com/s/ljh37o0a9mc50vjebw2nna6lwgq9w1yx)

**Comment by JennySanchez** [comment]
@larahanlon2 Can you take a look and let me know what do you think about Wonil's purposed content for updates?

**Comment by wonilsuhibm** [comment]
@JennySanchez @larahanlon2 just updated the story with a new Box note with updated content.

**Comment by JennySanchez** [comment]
@wonilsuhibm Can you add me to the new BOX note folder? I can not view it. Thank you.

**Comment by larahanlon2** [comment]
@wonilsuhibm hi! Can you also add me to the Box folder, please.

**Comment by wonilsuhibm** [comment]
@JennySanchez @larahanlon2 That's weird - it's the same Box folder at `IBM Digital Design Squad / Design / Website / _ _cupcake Website / Content + Design / 05 Patterns`. Just send you invites again.

**Comment by JennySanchez** [comment]
@wonilsuhibm Is this the file?
![Screen Shot 2020-01-07 at 8 22 50 AM](https://user-images.githubusercontent.com/45213839/71902091-f3fa3200-3126-11ea-89b4-49faf66f170d.png)

**Comment by JennySanchez** [comment]
Based on the feedback received during our share today, we need to take another look and decide what we need to work on to finalize the content for the update. 

The other question I have is what content we should include for the Overview page and what we should consider as the IBM.com specific layout guideline and have the content live under the Guideline category on the website.

I reserved 30 mins on our calendars for us to regroup on Monday 01/13 so we can be aligned on the next step.

**Comment by JennySanchez** [comment]
Via Lara after the discussion meeting:

"We are still making updates to it based on feedback last Thursday with IDL, Elliott, Carbon
It will need further reviews with the above folk before publishing I think the final content of this page will help us decide where it lives – whether it stays on the Layout overview page or if it gets a new page under guidelines."

---

👉 The definition of Guideline and the list of Guideline we need to add to the website work will be captured under issue #283.

**Comment by larahanlon2** [comment]
Feedback from IDL, Carbon and Elliott on Layout overview page [v 2.1.1](https://ibm.ent.box.com/notes/593977969328) (Thurs 9 Jan):

—
**Purpose** 
– This is a good section
– May not need visual schematics. They might be too confusing and prescriptive. 
– Consider just expressing the point in words.
– Be more high level in the guidance
– Consider: Editorial, Navigational, Messaging, Transactional
– Future goal to include more practical guidelines and resources 
– Mike: Is “reading” too abstract. Is it more “editorial” or “storytelling”. Need to get the intent for the user. 
– Elliott: need to include language around templates. Those templates meet the needs of the different page purposes. Direct adopters to use them. If the templates do not work/exist THEN the designers should design as per purpose.
– Be clear on who this is all for.

**2x Grid** 
– Add grid lines to show the vertical rhythm between the two examples

**Hierarchy** 
– Consider “content" hierarchy 
– For page level hierarchy examples consider Watson homepage 

**Next steps** 
– Take a step back
– Focus on **patterns** and move upward from there
– Focus on pattern level details and purpose
– Stacking and relationship with other patterns
– How they work together to form different types of pages
– Follow and use IDL layout tips and techniques content and images (eg. Watson patterns)

**Comment by larahanlon2** [comment]
Latest content updates and visuals WIP (v3.0.0) are [here](https://ibm.ent.box.com/notes/594294393853)!

**Comment by JennySanchez** [comment]
Task issue #288 created for finalizing the content as the next step.

**Comment by wonilsuhibm** [comment]
@larahanlon2 do we have a section on minimizing layout variations? something along the line of try not to use `1-1` => `1-3` => `2-2` => `3-3-10` => `2-8-4`?

**Comment by wonilsuhibm** [comment]
Maybe in this iteration, or in the next, but we should also talk about spatial model / areas. Be consistent in where areas for different functions are placed throughout your experiences.

**Comment by larahanlon2** [comment]
> @larahanlon2 do we have a section on minimizing layout variations? something along the line of try not to use `1-1` => `1-3` => `2-2` => `3-3-10` => `2-8-4`?

I added a small line to the 2x Grid section about this:
<img width="926" alt="Screen Shot 2020-01-17 at 5 32 12 PM" src="https://user-images.githubusercontent.com/53093550/72650735-50dbc080-394f-11ea-88e4-b46d75067e46.png">

 The current examples also illustrate this point but not to the same level of detail as the grid studies at the bottom of the page. 

After working through this iteration, I do think those grid/column studies go beyond just patterns – they apply to overall page and journey layouts. My feeling is that we need to consider how much of that info is enough for this overview page and what can we move under Guidelines section. Maybe.

**Comment by larahanlon2** [comment]
> Maybe in this iteration, or in the next, but we should also talk about spatial model / areas. Be consistent in where areas for different functions are placed throughout your experiences.

Definitely important. I'm trying to understand how that ties into layout **patterns** specifically. Would this kind of guidance be better suited to  page / template / journey level layout?
