### ISSUE TITLE
Cupcake website (Homepage) - post release dev fixes 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#245]
@jeffchew  Below are the collected items on the `Homepage` we need you or the dev team to take a look at. Please let me know if you have any questions.

PS: Please make sure we have the latest Gatsby Theme installed before you start on the tasks.

----

FYI - @wonilsuhibm @jacobottesen-dgc

**Comment by JennySanchez** [comment]
#### Homepage hero banner

- [ ] The CTA card size is too big and needs to be in the same size as the CTA card on Designing and Coding.
- [ ] The CTA card needs to be shifted to the edge.

![Screen Shot 2019-12-23 at 11 15 28 AM](https://user-images.githubusercontent.com/45213839/71371136-c4b7c280-2575-11ea-9490-6cfe08707dd0.png)

**Comment by JennySanchez** [comment]
#### Getting started section

- [ ] Designing and Coding CTA card location needs adjustment and shifted to the edge.
(Based on MIke's feedback via #191 - You can see how it should look like on the Carbon homepage)

![Screen Shot 2019-12-23 at 11 21 53 AM](https://user-images.githubusercontent.com/45213839/71371347-72c36c80-2576-11ea-8994-c05c6c32c171.png)

**Comment by JennySanchez** [comment]
#### Getting started/Designing 

- [ ] Update the mobile size image to be the one attached below.
Sketch work file can be found in the [BOX folder](https://ibm.box.com/s/gs0apv3kyopoiy72o3gphefbdm0op8xx) in case you need it.

![designing_mobile](https://user-images.githubusercontent.com/45213839/71371634-6c81c000-2577-11ea-96ab-f92552d25279.jpg)

**Comment by JennySanchez** [comment]
#### Update the upper right-hand menu

- [ ] we need to break the items down like what's on the [Carbon homepage](https://www.carbondesignsystem.com/)).

I think this is included in the Gatsby theme as well. 

---

![Screen Shot 2019-12-23 at 12 07 56 PM](https://user-images.githubusercontent.com/45213839/71373559-3e06e380-257d-11ea-8017-0e476f475af4.png)

**Comment by JennySanchez** [comment]
#### Latest update

- [ ] The  "Latest update" section cards should have `16 px` spacing in between them.

---

Our current set up on the website [Homepage](https://ibm-dotcom-library.netlify.com/) - Incorrect.
![Screen Shot 2019-12-23 at 12 20 29 PM](https://user-images.githubusercontent.com/45213839/71373979-a609f980-257e-11ea-9d40-5d7a35c0eb2d.png)


The way it should look like - Correct.
![Screen Shot 2019-12-19 at 2 42 51 PM](https://user-images.githubusercontent.com/45213839/71208082-e828f780-226d-11ea-8a36-94e12fcdbdac.png)

**Comment by mjabbink** [comment]
for section cards (Article Cards) you can see demo site here:
https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/ArticleCard

**Comment by mjabbink** [comment]
For the "Feature card" you can find demo here:
https://gatsby-theme-carbon-4dwiybdsa.now.sh/components/FeatureCard

**Comment by jeffchew** [comment]
All fixes have been completed: https://ibm-dotcom-library.netlify.com/

**Comment by mjabbink** [comment]
The color image in mobile is too lores. Should be svgs to avoid this.
