### ISSUE TITLE
Cupcake website (General) - post release dev fixes

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#246]
@jeffchew  Below are the collected items `in general after QA` we need you or the dev team to take a look at. Please let me know if you have any questions.

PS: Please make sure we have the latest Gatsby Theme installed before you start on the tasks.

----

FYI - @wonilsuhibm @jacobottesen-dgc

**Comment by JennySanchez** [comment]
#### Components/[Overview page](https://ibm-dotcom-library.netlify.com/components)

- [ ] The thin divider rule between cards is too light and it should be grey 20. See the Gatsby Resource Card example [here](https://gatsby-theme-carbon.now.sh/components/ResourceCard#example) for reference.


<img width="880" alt="Screen Shot 2019-12-12 at 6 22 02 PM" src="https://user-images.githubusercontent.com/32881239/70759545-528ce580-1d0c-11ea-9df1-0afbf5815e64.png">

**Comment by JennySanchez** [comment]
#### General spacing fix

- [ ] The space below the H2s across the website is inconsistent.
![Screen Shot 2019-12-18 at 11 36 26 AM](https://user-images.githubusercontent.com/45213839/71109381-ad9a5e80-218a-11ea-99f4-0d16648c5374.png)

**Comment by JennySanchez** [comment]
#### Update the action icons on the card
(Feedback from Mike)

- [ ] The action icons on the Help/[Overview page](https://ibm-dotcom-library.netlify.com/help) should be "Launch" icons instead of "ArrowRight" icons.
![Screen Shot 2019-12-31 at 12 10 26 PM](https://user-images.githubusercontent.com/45213839/71630052-9d40a580-2bc6-11ea-8463-48c353279193.png)

**Comment by JennySanchez** [comment]
👉 The action icons update for the cards is done and can be viewed [here](https://deploy-preview-250--ibm-dotcom-library.netlify.com/help).

**Comment by RobertaJHahn** [comment]
@JennySanchez Since you mentioned that the work will be done by the end of this week, I agree that we should keep it in sprint 24.  Since the cupcake release happened before the holiday, what release will they be included in?  There is a v1.1.0 or should I create a patch release?  @jeffchew

**Comment by jeffchew** [comment]
@JennySanchez can these be separated into separate stories/bugs? This would make it easier to track.

cc: @RobertaJHahn

**Comment by JennySanchez** [comment]
@jeffchew Task issue breaks into separate stories as requested - #1324 and #1325. Please add additional labels and settings to make sure we are good to go.

@RobertaJHahn We can close this one.

**Comment by RobertaJHahn** [comment]
This work has been broken into 2 stories.  Issue (#1324) and Issue (1325)  Closing this issue.
