### ISSUE TITLE
Dev fix: Homepage hero image set up and update the image

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#258]
#### Task
Our current homepage image is not displayed as intended and we need to adjust it.
- The image is scaled up too much and lose the full view of the image.
- The image looks pixelated, so we might need to see how we can display a higher quality image without adding too much image size to the page and impact the loading.

#### Additional information
Overall, we need the image to display at 100% for the desktop view. The current image is displayed less than 100% so we need to see what causes the display to not be at 100%.

(The final design for the hero image set up)

<img width="1158" alt="Screen Shot 2020-01-02 at 10 42 52 AM" src="https://user-images.githubusercontent.com/45213839/71679459-41545900-2d4d-11ea-8558-5dabc1673140.png">

(Current homepage hero image set up)

<img width="1673" alt="Screen Shot 2020-01-02 at 10 39 55 AM" src="https://user-images.githubusercontent.com/45213839/71679462-41ecef80-2d4d-11ea-9db2-5c8b9728390b.png">

**Comment by JennySanchez** [comment]
@jeffchew Let's take a look at the homepage hero image together before you start, please.

**Comment by JennySanchez** [comment]
@jeffchew Setting the estimate at 2 story points, please feel free to make any edits if my guessing is off. Thank you.

**Comment by JennySanchez** [comment]
@jeffchew You mentioned you might need to assign this task to a developer. Do you know who might be able to take on this task? Also, we need to let @RobertaJHahn know we need to move this task to Sprint 20-02.

**Comment by RobertaJHahn** [comment]
@JennySanchez @jeffchew moved issue to sprint 20-02.

**Comment by jeffchew** [comment]
Note, the homepage image has already been swapped out, but not sure if we are tracking issues around the style of it here or was there another issue to capture that @JennySanchez ?

cc: @kennylam @jacobottesen-dgc

**Comment by JennySanchez** [comment]
@jeffchew 

This issue contains two tasks:
1. Update the image
2. Correct how the image displayed

Is @kennylam going to work on this task? If it is, let's get on WebEx so I can show you what I am looking for, sounds good?

**Comment by JennySanchez** [comment]
@kennylam FYI: Set up a time for us to take a look together Friday. Thank you for working on this task with me!

**Comment by JennySanchez** [comment]
@kennylam Thank you for walking me through the homepage hero image setup. I wish I learn about it so much sooner. The image files are attached below as request and please feel free to let me know if you need anything else.

[_to Dev Team.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/4237103/_to.Dev.Team.zip)

**Comment by JennySanchez** [comment]
@kennylam I will move this to the "Done" column - FYI.
