### ISSUE TITLE
Use Hotjar survey for feedback collecting

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#260]
> As an IBM.com Library website content creator, 

> I need a way to collect adopter feedback

> so that I can resolve adopter pain points and make improvements to the Cupcake website.

#### Additional information
- Linda created a [Hotjar survey](https://surveys.hotjar.com/s?siteId=42920&surveyId=148553) for collecting feedback. Let's use the survey when we publish released our website. For now, let's think if we need to add anything else to the survey and record it as comments below.

![Screen Shot 2020-01-03 at 10.27.40 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/19138d68-ef2b-4e5e-96dc-1fc6de3f1556)

#### Acceptance criteria
- [x]  Have a list of the questions to review with Penny to get feedback.
- [ ]  Create a task issue for the dev team to update the questions.

**Comment by JennySanchez** [comment]
@ljcarot FYI on this task issue existed.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

Started brainstorming questions for the survey and sent them over to Penny for feedback on 01/17.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you add the questions here? I have no idea what questions are listed. :-(

**Comment by jacobottesen-dgc** [comment]
@JennySanchez 

Do you have questions after reviewing this page?
What questions do you still have after reviewing the FAQ page?
Is there unanswered questions you still have? Y/N Text input
After reviewing this page, what questions are still unanswered?

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Based on our discussion, can you come up with a list of general feedback survey questions and listed them here? I will do the same.

**Comment by JennySanchez** [comment]
I received a survey from the Hotjar company. It's focused on their homepage, but it a good reference.
![Screenshot_2020-01-24 Hotjar Survey.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/6d2767d5-67c7-4103-89af-61882b2199df)

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

Here is a great resource for survey/poll examples:
https://www.hotjar.com/blog/poll-examples/


How can we improve this site for you? Is anything missing?

—

If we could improve anything on this page what would it be?

—

What is your main purpose for visiting the IBM.com Library?

Which best describes you?

- Marketing designer
- DGC designer
- IBM Employee non designer
- Other 

—

Help us improve. Please rate this page.

What did we do well?

—

Were you able to find the information you were looking for?

**Comment by jacobottesen-dgc** [comment]
I created a box note with questions and resources: https://ibm.ent.box.com/notes/606305492632

I think we should brainstorm what research goals we have for the cupcake site.

cc. @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc I add comments to the box note you have and below are what I have. Let me know what do you think?

---

Thank you for sharing feedback with us. It will take three minutes and we appreciate your feedback. 

- [ ] Do you know where to find what you need on the website? (yes, or no)
- [ ] Do you know how to get in touch with the IBM.com library team to communicate your needs via the website? (yes, or no)
- [ ] What is your main purpose for visiting the IBM.com Library website? (comment box)
- [ ] If you have a magic wand and you can make any changes to the website, what would it be?  (comment box)
- [ ] How likely are you to share this website with your teammates or people who collaborate with you? (scale 0 to 10)

**Comment by ljcarot** [comment]
@JennySanchez @jacobottesen-dgc Do you have access to Hotjar?  It's super easy to create questions for survey. I can show you if you want to set up 30 minutes.

**Comment by JennySanchez** [comment]
I do. Sounds good and will do, @ljcarot <3!!!

**Comment by jacobottesen-dgc** [comment]
@JennySanchez The questions look great. Should we share them with Penny or are we good to add  them to Hotjar now?

**Comment by JennySanchez** [comment]
@jacobottesen-dgc We need to get feedback from Penny before adding it to the website next sprint.

**Comment by JennySanchez** [comment]
I reached out to Penny on Wednesday 01-29th and she did not get back to us yet. A new task issue (#260) is created for getting the questions finalized.

**Comment by JennySanchez** [comment]
@ljcarot @jacobottesen-dgc We are good to go with the Hotjar survey question updates. Please let me know if I missed anything before our work session next Tuesday.

---

**Thank you for sharing feedback with us. It will take three minutes and we appreciate your feedback.**

- Can you find what you need on this website? (yes, or no)
- If no, what information is missing? (comment box) 
- Do you know how to get in touch with the IBM.com library team to communicate your needs via the website? (yes, or no)
- If you had a magic wand, what changes would you make to this website?  (comment box) 
- How likely are you to share this website with teammates or collaborators? (scale 0 to 10)
