### ISSUE TITLE
Footer component design update

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/ibm-dotcom-library-website#262]
Disregard content in the attached visuals but look to the structure and placement of content. Still maintains a column structure.

**Default:**

<img width="958" alt="Screen Shot 2019-12-14 at 5 16 50 PM" src="https://user-images.githubusercontent.com/32881239/71739713-d7f14a80-2e1f-11ea-8441-f8a4c073a1d6.png">

**Minimal:**

<img width="956" alt="Screen Shot 2019-12-14 at 7 19 20 PM" src="https://user-images.githubusercontent.com/32881239/71739674-b42e0480-2e1f-11ea-8b46-2a11cc425d4a.png">

**Comment by mjabbink** [comment]
<img width="1122" alt="Screen Shot 2020-01-03 at 11 56 17 AM" src="https://user-images.githubusercontent.com/32881239/71739793-1555d800-2e20-11ea-918f-268fcd45fc4f.png">

**Comment by wonilsuhibm** [comment]
This is a duplicate issue. Will move the missing minimal design piece to the existing ticket (https://github.com/carbon-design-system/ibm-dotcom-library/issues/860)
