### ISSUE TITLE
Create consistent icons rules for cupcake site

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library-website#275]
#### User Story

> As a Cupcake website content creator

> I need to: clear consistent icon labels on the cupcake site

> so that I can: correctly navigate throughout the site.

#### Additional information
I am working on icon rules to bring consistency to the resource cards on the cupcake site. 

#### Acceptance criteria
- [ ] Reviewed with Jenny and approved by Wonil.
- [ ] Share findings with the Carbon team.

**Comment by jacobottesen-dgc** [comment]
Made an update to the site. If we don't like the icon ruling I can change it back

Live link: https://ibm-dotcom-library.netlify.com/resources#color-grid-and-icons

![Screen Shot 2020-01-09 at 2.34.04 PM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/4a788656-f793-491b-9d0d-9d8f8dcd42ad)

**Comment by JennySanchez** [comment]
Nice work, @jacobottesen-dgc . Please share our findings with Jan and Connor on the Carbon Team.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you schedule a time this week to share the finding with Jan Child (Content Design Lead) and Connor Leech (Content Designer) and have me as optional on the invite? 

Let me know if you have any questions.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Schedule meeting for Thursday from 10:30-10:45am.

**Comment by JennySanchez** [comment]
@wonilsuhibm Here's the final general icon usage rule for the website

- **right arrow icon:** links within the cupcake site (resource card link on the Get started/Overview page to Resource page).
- **launch icon:** leaving the cupcake site (Github, Storybook, Box)
- **download icon:** anything that can be linked to downloads asset or tool (Sketch kit download from Sketch Cloud)

Let us know if we missed anything.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez @wonilsuhibm 

Had a meeting with Connor from Carbon on 01/16. 

- Sent him the icon proposal
