### ISSUE TITLE
Demo window feature mapping study

### ISSUE THREAD

**Issue by jacobottesen-dgc** [carbon-design-system/ibm-dotcom-library-website#276]
#### User Story

> As a Cupcake website content creator

> I need to: prioritization features for the demo window

> so that I can: focus on building the best features first.

#### Additional information
I am working on prioritizing features for the demo window

#### Acceptance criteria
- [x] Reviewed and approved by Wonil & Jenny

**Comment by JennySanchez** [comment]
@wonilsuhibm FYI on this study task existed.

**Comment by jacobottesen-dgc** [comment]
I reviewed a few component demo windows on other design systems. I gathered the list of potential features for our demo page and prioritized based on user impact and dev feasibility. 

![Feature_mapping_demo_small.jpg](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/d2a2d01a-9352-409b-9af2-6896f7ba5772)


cc. @wonilsuhibm @JennySanchez

**Comment by jacobottesen-dgc** [comment]
Here are some explorations for the responsive demo window:

![Responsive option 1.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/a72e7d60-f387-477f-9894-770d77f8db4d)

![Responsive option 2.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/beaa3f27-8770-4910-863d-6a49ca31fed9)

**Comment by JennySanchez** [comment]
@wonilsuhibm Is this close to what you have in mind for feature mapping? Any feedback for Jacob to move forward with this study?

**Comment by JennySanchez** [comment]
**Update:** Review meeting scheduled for 01/14.

**Comment by jacobottesen-dgc** [comment]
Update: Presented work to the team 1/14/20.
