### ISSUE TITLE
Add Tealium and Hotjar scripts to Cupcake website pages

### ISSUE THREAD

**Issue by ljcarot** [carbon-design-system/ibm-dotcom-library-website#279]
In order to get metrics and hotjar working on Cupcake website, we need to add Tealium to the pages beginning with https://ibm-dotcom-library.mybluemix.net/ and all sublevels.  

Additional Information:
IBM Common metrics script added to the page.  It should include both Telium and Hotjar
[ibm common.js](https://1.www.s81c.com/common/stats/ibm-common.js)

Acceptance criteria:
Pages will appear with Hotjar tag enabled
Pages will appear in Pearl metrics dashboard.

**Comment by JennySanchez** [comment]
FYI - @jeffchew

**Comment by ljcarot** [comment]
@JennySanchez is this the dev story you were looking for earlier today?

**Comment by JennySanchez** [comment]
@ljcarot You are right! I thought I saw this issue somewhere before but can not find it. Thank you!!!

**Comment by jeffchew** [comment]
Added ibm-common.js to the bottom of the page.
