### ISSUE TITLE
Cupcake website page creation - Patterns/Lead Space page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#28]
#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via #1664.
- Lead Space page on v19a website Components section can be viewed [here](https://www.ibm.com/standards/web/components/lead-space/).
- Carbon does not have Lead Space as a component or patterns.
(Anna mentioned - "Only the gatsby template has that. We don't have that for product.")

#### Task
- Collaborate with Lara for the content creation.
- Content draft box doc can be found [here](https://ibm.box.com/s/gyvd3zvxl4vdf1rk0u2y65obceg1c2mp)

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

**Comment by JennySanchez** [comment]
**Storybook for Cards** = https://deploy-preview-78--ibmdotcom-patterns-react-experimental.netlify.com/?path=/story/leadspace--default-with-image

**Comment by JennySanchez** [comment]
@RobertaJHahn FYI - We need to move this to Sprint 23.

**Comment by JennySanchez** [comment]
**Content draft for Lead Space:**
https://ibm.box.com/s/gyvd3zvxl4vdf1rk0u2y65obceg1c2mp

**Comment by JennySanchez** [comment]
Hi @larahanlon2 , I know you need to add image breakpoint notes still, but if there's anything I can start the publishing process with, please let me know. :-)

**Comment by larahanlon2** [comment]
@JennySanchez snap. I just added that info 20mins ago!

@wonilsuhibm do you think Jenny can start publishing what is in the [Box note](https://ibm.ent.box.com/notes/528552262380)? We could continue to edit and refine but it might be helpful to see it in Gatsby as we do that?

**Comment by JennySanchez** [comment]
**Update:** Content reviewed with Jacob and will start the publishing process today.

@RobertaJHahn Sprint 23 ends tomorrow. Please change the Milestone label to Sprint 24 - FYI.

**Comment by RobertaJHahn** [comment]
@JennySanchez issue moved to sprint 24

**Comment by JennySanchez** [comment]
**Items to discuss with Lara:**
- Imagery/Usage: setup
<img width="758" alt="Screen Shot 2019-12-06 at 5 18 09 PM" src="https://user-images.githubusercontent.com/45213839/70364108-cdf42000-1850-11ea-98f6-9d7d367a8b3e.png">

- Border for the images
(should we add a border or not? If yes, Gray 30 (c6c6c6)?
( see Jacob's Sketch file for reference)

- Follow up on "Specifications" images.
(need updated image with white background)

- Style options section. Should we take out "Style option tile and make Left-aligned as H2 and Content guidance as H3. 
<img width="881" alt="Screen Shot 2019-12-06 at 5 45 45 PM" src="https://user-images.githubusercontent.com/45213839/70364239-4c50c200-1851-11ea-96ca-49c3647f792f.png">

**Comment by JennySanchez** [comment]
@jacobottesen-dgc  FYI - Discussion scheduled for 12/09 Monday.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Can you make a review outcome update here?

**Comment by jacobottesen-dgc** [comment]
@JennySanchez I talked with Lara and here are the outcomes:

- She will get the spec images by EOD
- She wanted left aligned to be h2 but add style options to the end so "Left-aligned style options"

**Comment by larahanlon2** [comment]
@jacobottesen-dgc @JennySanchez here's my markup of the current page. 99% of this was covered with Jacob during our call (and thank you Jacob for making some changes already!). Please take a look and let me know if we need to discuss.

![lead space -- cupcake -- page review 01](https://user-images.githubusercontent.com/53093550/70491311-f5f0b700-1ace-11ea-9a1f-e12c3a478bfd.jpg)

**Comment by larahanlon2** [comment]
Is there any way we can include anchor links at the top, like before?

**Comment by jacobottesen-dgc** [comment]
@larahanlon2 Jenny said that Carbon is planning to remove the anchor links so we will not have them at this time. Reach out to her for more info.

cc. @JennySanchez

**Comment by JennySanchez** [comment]
@larahanlon2 We are not using the anchor link feature in Cupcake v1.0. Some of the changes are good to go but some of them are not what we can control with the code. Let's chat.

**Comment by JennySanchez** [comment]
This task is completed. Items need to be fixed are recorded in the dev fix issue #63.
