### ISSUE TITLE
Content Planning - What is a guideline and what guidelines we are going to create for 2020

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#283]
> As an IBM.com Library website content creator, 

> I need a way to help adopters understand what is a guideline and provide guidelines specificity to their day to day work 

> so they can work on their day to day tasks without confusion.

#### Additional information
We need to find answers on the following two areas:
- What is a guideline?
- What guidelines are needed specifically for IBM.com adopters?

#### Acceptance criteria
- [x]  Have an agreed definition of what a guideline is from the team.
- [ ]  Have a list of the guidelines we can update the website sitemap with and make plans for content creation.

**Comment by JennySanchez** [comment]
@wonilsuhibm @larahanlon2 @oliviaflory FYI on this task issue created based on our conversation today.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc @j1mie FYI on this is the task for the Guideline section content planning as mentioned today.

**Comment by JennySanchez** [comment]
**Task update:**
- @jimpistilli Studied Guideline section on the Carbon website and quick huddle scheduled for tomorrow.
- Reached out to a few adapters to get input around the guidelines they need.
- Set up a [Mural board](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94) with Wonil to capture the content needs from the adopters.

**Comment by JennySanchez** [comment]
### Findings

---

**What is a guideline mean to you?**
Guidelines are a series or collections of structured rules/methodologies to align tasks: design, copy, process, reviews, etc. Guideless are not strict but rather served as a guidance with welcomed opportunity to challenge the set rules/methodologies based on team-wide reviews.
 
**Besides the guidelines you see on the Carbon website,(see screenshot below) what other guidelines do you think IBM.com Library team should provide to help you with your day to day work?**
There are certain UI / UX scenarios in any design kit components where it is not explained in detail. Examples: proper overhanging UI (background, borders, icons, etc), things we CAN and CAN NOT do when designing amongst v18 / v19 / Carbon design kits as some rules/methodologies are more strict/linent than others (alignment of text and icons, column alignment, etc)

---
**What is a guideline mean to you?**
To me a guideline explains how things work. It gives rules of what to do and what not to do and explains why. If applicable, it has good examples and easy ways to get started following the instructions. It may also include helpful tips and try to clarify ambiguity. (I may be slightly biased because I am working on the Illustration guidelines).

**Besides the guidelines you see on the Carbon website,(see screenshot below) what other guidelines do you think IBM.com Library team should provide to help you with your day to day work?**
I cannot think of anything at the moment that I am missing from this list. If we did come up with a standard design spec style maybe that could be included. It is something I personally do a lot of but I am not sure how important standardizing it is. Separately, I know Wonil is working on a high level view of page layouts across our teams I could see something like that potentially being useful at some point too or could be folded into working with the 2x grid.

**Comment by jimpistilli** [comment]
@JennySanchez Hey there - below is a draft of a proposed Guidelines page, hopefully capturing the opinion research posted above and what we discussed this morning. Will stand by for further edits or if you want to discuss.

https://ibm.box.com/s/3ax36nqvhauoid6ha47ybv37qk70mcuk

**Comment by JennySanchez** [comment]
@jimpistilli 

The overall content looks good but we need to add something to answer what is guideline then move into "These guidelines have been adopted from dedicated design and UX professionals’ work product that are..."

We went over the overall set up of the page will look like, but I quickly mock it up as a visual reference so you know what to expect and how we can make the edit of the copy you have to work with the setup.

![Guideline Overview Page - visual reference](https://user-images.githubusercontent.com/45213839/73291213-5fcf3800-41c5-11ea-8fa0-98fef2692cab.jpg)

**Comment by jimpistilli** [comment]
@JennySanchez Updated with v2, as we discussed: https://ibm.ent.box.com/file/606383571632

**Comment by JennySanchez** [comment]
(Draft from Jim)
#### Guidelines 

 

[Overview] 

 

What are guidelines? 
 

Tools, building blocks and simplified processes specifically designed for the IBM.com Library, these parameters can be defined as guidelines that were conceived to provide clarity and remove ambiguity in building digital products and experiences. Practically, these goals are achieved by conveying a symmetrical and concise user interface that maximizes a web visitor’s time efficiently.  

 

These guidelines have been adopted from dedicated design and UX professionals’ work product that are set out to standardize the IBM online experience across all business units. They are written from a perspective of providing an engaging, functional and visually appealing web experience. This is achieved through building reader familiarity and consistency across all of IBM’s pages, while informing and educating about IBM products and services.  

 

These guidelines are open to interpretation, your interpretation. We leave it to you, the IBM.com Library adopter, to implement these rules to best meet the demands of your BUs and stakeholders, while applying your individual design vision. Use these guidelines as a roadmap and as a series of best practices. Any design functionality that you may interpret apart from these guidelines should be data-driven and supported by established practical experience.

**Comment by wonilsuhibm** [comment]
@JennySanchez @jimpistilli Thank you. It reads very nice. My one concern is that it might be too verbose. The main content is the list below, I'd love to see this condensed into one short and sweet paragraph.

**Comment by jimpistilli** [comment]
Sure, I can pare it down to a lighter reading paragraph, will circle back.

**Comment by jimpistilli** [comment]
Hey @wonilsuhibm - below is an updated version, reflecting your request. Please let me know if you're good with this or if it still needs some work.  Thanks.

**What are guidelines?** 
 
The guidelines found here can be defined as a set of parameters that are designed to provide clarity and remove ambiguity in building digital products and experiences. They are written with the intent to build reader familiarity and consistency across all of IBM’s pages, while educating about IBM products and services. We leave it to you, the IBM.com adopter, to implement these best practices to meet the demands of your BUs and stakeholders, while applying your individual design vision. Any design functionality that you may interpret apart from these guidelines should be data-driven and supported by established practical experience.  

cc: @JennySanchez

**Comment by JennySanchez** [comment]
We will work on the next step via #304.
