### ISSUE TITLE
Guidelines page research

### ISSUE THREAD

**Issue by jimpistilli** [carbon-design-system/ibm-dotcom-library-website#293]
Conduct supporting research of Guidelines pages in order to write new content for forthcoming additional Guidelines pages. 

https://www.carbondesignsystem.com/guidelines/2x-grid/basics/

**Comment by jimpistilli** [comment]
This is related to story #283

**Comment by jimpistilli** [comment]
First draft sent to @JennySanchez on 01.27 and available here: https://ibm.ent.box.com/file/606383571632

**Comment by JennySanchez** [comment]
@j1mie Let's move this task issue to the "Done" Column since we are moving on to the content crafting via #283 as the next step from here.
