### ISSUE TITLE
Pattern demo component: design study

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library-website#296]
### User story
As a maker of IBM.com pages and templates, I need a way to preview a layout pattern, play with it, and understand its interactive and responsive behaviors.

### Notes
- This story is to do UX design.
- We have a design that was done a long time ago. This design doesn't align with the Carbon team's component demo tool's design at the moment. We should try to align as much as possible.
- We have done some initial user research in carbon-design-system/ibm-dotcom-library#684

### Acceptance criteria
- [x] Wireframes have been produced, reviewed, and accepted.

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez @wonilsuhibm 

Created a prototype for a potential layout patterns demo window: https://projects.invisionapp.com/share/BGVPD1Z34Q8#/screens/402194981

**Comment by JennySanchez** [comment]
@jacobottesen-dgc @wonilsuhibm Do you have the next step in mind from this sprint's work? If you do, can you create a task issue on the website board for it and let me know by Friday? Thank you.

**Comment by wonilsuhibm** [comment]
@jacobottesen-dgc this looks great! So excited to see this. 

A few questions:

- Being able to see the specs was another ask. Are you thinking that specs would be handled separately?
- Desktop view loses the knobs and the content editor. Is there any way to keep them?
- How do you imagine responsive layouts would be handled? Are these patterns fixed at the three device sizes? Or do they respond to browser size?

**Comment by jacobottesen-dgc** [comment]
**Desktop view loses the knobs and the content editor. Is there any way to keep them?**

I did explore an option where entering desktop view would be a bit different. Or you could keep the same layout as a prototype above and add the knobs to the desktop view. I'd love to hear your thoughts. 

![Screen Shot 2020-01-30 at 9.54.19 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/45ef7d55-0caf-490f-9120-0a2c0ed9d973)

**Comment by jacobottesen-dgc** [comment]
**How do you imagine responsive layouts would be handled? Are these patterns fixed at the three device sizes? Or do they respond to browser size?**

I worked through the responsive design in the image below. When using a 700px-680px device the desktop view option would be removed. If they were to select the tablet view it would open full screen in their 700px-680px device size. Let me know if you have questions. 

![Screen Shot 2020-01-30 at 10.07.13 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/3128d6e6-9253-4ded-bb6e-166b5f168caa)

cc. @wonilsuhibm

**Comment by jacobottesen-dgc** [comment]
**Being able to see the specs was another ask. Are you thinking that specs would be handled separately?**

Still work through this. Updates coming soon

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Please provide the updates here and move on to the next step for this task with #972.

**Comment by jacobottesen-dgc** [comment]
Just received feedback from Wonil this morning. 
Current sketch file: https://ibm.box.com/s/1ojy3cthxk82gr88xnvht2vg8myhy57d

Next steps:
- Title at top in full screen view 
- Changing pattern type to higher level 
- Implement ontology patterns
- Specs

**Comment by JennySanchez** [comment]
Perfect. Thanks.
