### ISSUE TITLE
Finalize Guideline overview page content for the website update

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#304]
The planning detail can be viewed via #283

---

> As an IBM.com Library website content creator, 

> I need a way to help adopters understand what is a guideline and provide guidelines specificity to their day to day work 

> so they can work on their day to day tasks without confusion.

#### Steps:
- [x] Share the draft with the team to get feedback
- [ ] Finalize the content
- [ ] Publish the content on website with markdowns

#### Acceptance criteria
- [ ]  Have the what is guideline content finalized and published on the live website.

**Comment by JennySanchez** [comment]
As 01-29-2020

---

#### Guidelines 

 

[Overview] 

 

What are guidelines? 
 

Tools, building blocks and simplified processes specifically designed for the IBM.com Library, these parameters can be defined as guidelines that were conceived to provide clarity and remove ambiguity in building digital products and experiences. Practically, these goals are achieved by conveying a symmetrical and concise user interface that maximizes a web visitor’s time efficiently.  

 

These guidelines have been adopted from dedicated design and UX professionals’ work product that are set out to standardize the IBM online experience across all business units. They are written from a perspective of providing an engaging, functional and visually appealing web experience. This is achieved through building reader familiarity and consistency across all of IBM’s pages, while informing and educating about IBM products and services.  

 

The parameters set forth here are open to interpretation, your interpretation. We leave it to you, the IBM.com Library adopter, to implement these rules to best meet the demands of your BUs and stakeholders, while applying your individual design vision. Use these guidelines as a roadmap and as a series of best practices. Any design functionality that you may interpret apart from these guidelines should be data-driven and supported by established practical experience.

**Comment by JennySanchez** [comment]
@j1mie FYI - we will share the content in our Huddle 2020: squad weekly on 02/06 to get feedback from the team.

**Comment by jimpistilli** [comment]
Updated copy:

_The guidelines found here can be defined as a set of parameters that are designed to provide clarity and remove ambiguity in building digital products and experiences. They are written with the intent to build reader familiarity and consistency across all of IBM’s pages, while educating about IBM products and services. We leave it to you, the IBM.com adopter, to implement these best practices to meet the demands of your BUs and stakeholders, while applying your individual design vision. Any design functionality that you may interpret apart from these guidelines should be data-driven and supported by established practical experience._

**Comment by jimpistilli** [comment]
Hey @wonilsuhibm - if you approve of the revise text, would you let us know so we can proceed in getting the copy on the page?  Thanks.

**Comment by wonilsuhibm** [comment]
@jimpistilli @JennySanchez Thank you. Looks good to me.

**Comment by JennySanchez** [comment]
After the update went on the staging site, Jim and I took a look and realized:
- We do not need the "About the guidelines" section title and should take out the intro paragraph and use the updated content for the intro. 
- We need to take out the  "Guidelines are a set of fundamentals that bring consistency to IBM’s product and online experiences." under the "Core guidelines".
- We do not need the Principles section and should take it off as well.

![Screenshot_2020-02-05 IBM com Library(1)](https://user-images.githubusercontent.com/45213839/73867477-6afd1600-480c-11ea-907a-a441c90e04c1.png)

**Comment by JennySanchez** [comment]
Guideline page update completed and can be viewed on the [website](https://ibm-dotcom-library.mybluemix.net/guidelines).
