### ISSUE TITLE
Update title & subtitles on resource cards set up on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#308]
> As a cupcake website content creator

> I need to find out resource card titles and subtitles ruling

> So that I can make sure our website content is 100% aligned with the Carbon website.

### Additional information
- Research and planning detail can be viewed via #285

#### Acceptance 

- [ ] Update all resource card set up on the Cupcake website.
- [ ] Review the update with Jenny.

**Comment by jacobottesen-dgc** [comment]
All resource cards have been audited and updated to the new titling style. This task is ready for review @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Card titles on the [Get Started / Overview page](https://ibm-dotcom-library.mybluemix.net/getting-started) are the ones we need to take another look.

![Screen Shot 2020-02-21 at 11 10 23 AM](https://user-images.githubusercontent.com/45213839/75058445-a0f2f900-54a0-11ea-88de-7702781c7038.png)

The card titles on this page are different than the rest because they start with "start" and "find". If we want to keep the consistency, maybe have them as "For designing", "For coding", "Additional resources", and "Help".

**Comment by jacobottesen-dgc** [comment]
All updates have been added to the site. Feel free to review and move to done. 

cc. @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Thanks!
