### ISSUE TITLE
Content publishing process audit & analysis

### ISSUE THREAD

**Issue by jimpistilli** [carbon-design-system/ibm-dotcom-library-website#313]
Acceptance criteria: Assess our processes of publishing content for both efficiency and speed, and also align the content itself to what our adopters' needs and wants are.

Definition of done: An audit and analysis of our content publishing process, start to finish, that includes suggestions to improve and for it to be as relevant as possible.

cc: @JennySanchez @wonilsuhibm

**Comment by JennySanchez** [comment]
Hi, @jimpistilli I saw the story point setting is at 21. It seems really high, can you confirm? Thank you.

**Comment by jimpistilli** [comment]
@JennySanchez Corrected that to a 5, if you think that's accurate.

**Comment by JennySanchez** [comment]
@jimpistilli The draft of the website content publishing process and timeline can be found [here](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj).

The document is created based on Lara's pattern content publishing roadmap document. 
The focus here is to make sure the steps look correct and the timelines look reasonable.

**Comment by jimpistilli** [comment]
@JennySanchez Reviewed and made a few edits but overall looks good to me.

**Comment by JennySanchez** [comment]
@jimpistilli Got it. Thank you for reviewing the doc.
