### ISSUE TITLE
New homepage website hero message

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#318]
#### User story
> As an IBM.com Library website designer, 

> I need a way to present the purpose of the IBM.com Library on the homepage hero area

> so that our adopter can understand the purpose of IBM.co Library right away.

#### Additional information 
- The homepage design is not finalized but the image below can be used as a visual reference for copy creation.

![Screen Shot 2020-02-11 at 11 48 20 AM](https://user-images.githubusercontent.com/45213839/74263453-78ab1380-4cc4-11ea-95ae-03468da01b85.png)

#### Tasks
- [ ] Provide a few copy options for review

#### Acceptance criteria
- [ ] Copy finalized for homepage design mockup.

**Comment by JennySanchez** [comment]
@j1mie 

**Our current intro on the Cupcake website homepage:**
"IBM.com Library is a collection of components, patterns, tools, and guidelines for designers and developers building IBM.com experiences. Its components and patterns are based on Carbon Design systems and optimized to help our adopters building the best IBM.com experiences."

---

Here are a few ideas to help you get started, please let me know if you have any questions about the task.

- IBM.com Library is a collection of components, patterns, tools, and guidelines for building
- IBM.com experience.

(Refined by Jim - "The IBM.com Library is a set of guidelines to create the IBM.com web experience." or shorter "The IBM.com Library are guidelines to create the IBM.com web experience.")

- The single source of truth for the IBM.com experience creation.
- Build delightful IBM.com experience, easier.
- Design, develop, and deliver IBM.com experience easier and faster.
- Create straightforward and beautiful experiences for IBM.com users.
- Create intuitive and beautiful IBM.com experiences that start here.
- Your foundation to build a thoughtful IBM.com experience.
- Let's build functional and beautiful IBM.com experiences.
- Streamline your IBM.com experience creation.

**Comment by JennySanchez** [comment]
@wonilsuhibm Please let Jim and I know if you have any thoughts on the copy to help us get started.

**Comment by jimpistilli** [comment]
@wonilsuhibm The original copy is _IBM.com Library is a collection of components, patterns, tools, and guidelines for building IBM.com experience._

Shorter versions I suggested as Jenny described above are:

- _The IBM.com Library is a set of guidelines to create the IBM.com web experience._

- _The IBM.com Library are guidelines to create the IBM.com web experience._

If you're looking for something more descriptive, I don't think it will be as brief.

cc: @JennySanchez

**Comment by JennySanchez** [comment]
@jimpistilli I am looking for something else other than what we had. Let's chat Thursday before you start on the task - Calendar invite on the way.

**Comment by JennySanchez** [comment]
@jimpistilli Here are the purposed designs we went over today - add them here for your references.

![Screen Shot 2020-02-14 at 2 28 43 PM](https://user-images.githubusercontent.com/45213839/74567004-6afec380-4f3a-11ea-82b4-cbbc73c6a33f.png)
![Screen Shot 2020-02-14 at 2 56 45 PM](https://user-images.githubusercontent.com/45213839/74567012-6e924a80-4f3a-11ea-87a1-db6c64670ad5.png)

**Comment by jimpistilli** [comment]
@JennySanchez Below are some ideas. I think we should try to narrow down the two adjectives you like best / best describes the site and then we can tinker with the wording. 

- The IBM.com Library is a set of guidelines to create the IBM.com web experience.
- The IBM.com Library are guidelines to create the IBM.com web experience.
- Build functional and meaningful IBM.com experiences.
- Start here to create a practical and expressive IBM.com web experience.
- Your starting point for essential and functional IBM.com experiences.
- Design, develop and deliver the IBM.com experience efficiently and practically.
- Guidelines for intuitive and informative IBM.com experiences.
- Get started designing the IBM.com experience here.


cc: @wonilsuhibm

**Comment by JennySanchez** [comment]
@jimpistilli I will take a look and pick two for the proposed designs.

**Comment by JennySanchez** [comment]
@wonilsuhibm I picked "Build functional and meaningful IBM.com experiences." for style one and "Your starting point for essential and functional IBM.com experiences." for style two. 

👉 You can see mockups with the copy implemented via #327.

Let me know if there are any other ones from Jim's list you prefer to see in the mockups.
