### ISSUE TITLE
Content creation: FAQ page - What are the differences between Card vs Tile

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#321]
#### User story
> As an IBM.com Library website designer, 

> I need a way to help adopter understand what are the differences between a Card vs a Tile,

> so that our adopter can correctly use the components.

#### Additional information 
- Carbon tile components can be viewed [here](https://www.carbondesignsystem.com/components/tile/code)
- Please work on this with @oliviaflory 

#### Tasks
- [x] Craft the question and answer

#### Acceptance criteria
- [ ] The finalized question and answer are ready to be published on the live website.

**Comment by oliviaflory** [comment]
@jimpistilli here is some tile vs card examples, I am guessing for the FAQ page we'd want to distill the information down to a simple sentence or three. I wanted to give you all these examples and usage so you could have a good understanding. 

cc @larahanlon2 @wonilsuhibm let me know if I've missed anything or you have any changes

---
### Tile
A tile is a core component in the design system, see Carbon documentation [here](https://www.carbondesignsystem.com/components/tile/usage)
*"Carbon ships a basic tile structure that responds to the grid. **Tiles have no pre-set styles for the content within them.** You can customize tiles to fit your specific use case."*

There are multiple types or variants of a tile:
- default (read only)
- clickable
- selectable
- expandable

Usage:
- foundation for a Card pattern
- contain related content


### Card
A card is a pattern that encompasses / defines / is coded with all pre-set styles eg. type styles, image, icon.

Cards can have many different combinations of content / pre-set styles
- eye brow
- heading
- body copy
- icon
- images

Usage:
- [Feature card](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default): used to highlight a single piece of information
- [Content group cards](https://ibmdotcom-react.mybluemix.net/?path=/story/patterns-blocks-contentgroupcards--default): Used to group a collection of related content 


<img width="424" alt="Screen Shot 2020-02-13 at 12 27 23 PM" src="https://user-images.githubusercontent.com/45692622/74461473-94492200-4e5c-11ea-86b3-f785f20ec69b.png">

<img width="694" alt="Screen Shot 2020-02-13 at 1 01 15 PM" src="https://user-images.githubusercontent.com/45692622/74467836-d166e180-4e67-11ea-8fd1-0e3f6f7d192e.png">


<img width="1190" alt="Screen Shot 2020-02-13 at 12 29 37 PM" src="https://user-images.githubusercontent.com/45692622/74461480-97441280-4e5c-11ea-9880-b62632b9628d.png">

In context examples:

**Content Group with Cards**
<img width="591" alt="Screen Shot 2020-02-13 at 2 11 25 PM" src="https://user-images.githubusercontent.com/45692622/74469553-e1cc8b80-4e6a-11ea-84b2-2f76e792628f.png">

**Feature Card**
<img width="457" alt="Screen Shot 2020-02-13 at 2 11 51 PM" src="https://user-images.githubusercontent.com/45692622/74469579-ebee8a00-4e6a-11ea-8e43-2b9d664540e8.png">

**Another feature card**
<img width="510" alt="Screen Shot 2020-02-13 at 2 11 56 PM" src="https://user-images.githubusercontent.com/45692622/74469582-ee50e400-4e6a-11ea-8361-3ad928a8688e.png">

**Comment by jimpistilli** [comment]
@oliviaflory Thanks for the info. Will try to summarize in just a couple of sentences. 

cc: @JennySanchez @wonilsuhibm

**Comment by jimpistilli** [comment]
Hey @oliviaflory and @wonilsuhibm - below is a Box link to a first draft of the Cards vs. Tiles FAQ explainer. I'm clear on the differences and hopefully accurately described in a brief explainer. Though I did leave a note in the comments checking if we have a for more info link on Cards, as we do with Tiles.  Thanks

https://ibm.ent.box.com/file/618860360487

cc: @JennySanchez

**Comment by oliviaflory** [comment]
Thanks @jimpistilli for the draft, per your question about the Card documentation link:

- Carbon's definition of Tile and Cards overlaps a bit, though it is similar to ours, Carbon does not provide any _preconfigured_ card patterns like we do in the IBM.com Library.

- I would rather not link to their definition of Cards since it is experimental and doesn't follow our specific guidelines.

- I wonder if we could hold off on publishing this until we have a chance to document our Cards.
@JennySanchez  are we getting feedback from the adopters that they don't know how to use the tile and cards?

**Comment by jimpistilli** [comment]
@oliviaflory Thanks for reviewing but would you mind clarifying "_Carbon does not provide any preconfigured card patterns like we do in the IBM.com Library_"

As that sounds a bit contradictory to the info you posted above that says:

_Cards can have many different combinations of content / pre-set styles_

So they can be "preset" styles but can _not_ be "preconfigured"?  Is it just a matter of word usage of set over configured? Thanks. 

cc: @JennySanchez @wonilsuhibm

**Comment by JennySanchez** [comment]
@oliviaflory 

This task existed because we got feedback awhile back from the adopters that they are confused "title" and "card". 

We can get feedback from the adopters to validate if this is still a challenge for them once they have a chance to see the card pattern content. 

---

@jimpistilli 
"Tile" is one of the core components and "Card" is one of the layout patterns in the IBM.com Library.  The Card pattern could be composed of a group of tiles. Since they are not both a "component" nor both a "pattern" that's why this is challenging for adopters.

Is the content below the latest?


" **What is the difference between a Card and a Tile?** 
Cards and Tiles are similar in appearance, but the difference between the two can be summarized by there is no predefined style for the content within a Tile, while a Card’s style is preconfigured. Tiles can be tailored to adapt to your use case and Cards cannot.  

Please visit here for more information about Cards, and here, for more information about Tiles."

**Comment by jimpistilli** [comment]
@JennySanchez Below is what the last version of the suggested copy we have is currently:

**What is the difference between a Card and a Tile?**
Cards and Tiles are similar in appearance, but the difference between the two can be summarized by there is no predefined style for the content within a Tile, while a Card’s style is preconfigured. Tiles can be tailored to adapt to your use case and Cards cannot.

**Comment by JennySanchez** [comment]
@jimpistilli Thanks. 

**Next Step:** We will keep the content for now and do an adopter feedback session in Q2 and come back to this.
