### ISSUE TITLE
Website pages anchor links implementation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#325]
> As an IBM.com Library adopter, 

> I need a way to see what content is included in this page and I can be taken to the section right away

> so that I can find the specific information on the page I need and move on.

#### Additional information
- After talking to Jeannie on the Carbon Team, the page anchor link will not go away.
- To create a better content browsing experience, we need to set up anchor links (see highlighted area below) to help the adopter get to the information they need as quickly as we can.

![Artboard](https://user-images.githubusercontent.com/45213839/74388243-8b0a7780-4dc0-11ea-8e9a-e04de9d7edfc.jpg)

#### Acceptance criteria
- [ ] Content page anchor links are implemented on the live website.

**Comment by jacobottesen-dgc** [comment]
All anchor links have been added to the [live site](http://ibm-dotcom-library.mybluemix.net/getting-started) but not all are working. I talked with Vince on Carbon and he said we need to update to the latest Gatsby theme and the links should work.

@jeffchew Could you update our site to the latest Gatsby theme? Thanks!

CC. @JennySanchez

**Comment by JennySanchez** [comment]
@jacobottesen-dgc I clicked on most of the links and it worked.

**Comment by JennySanchez** [comment]
I am not sure if there's a best practice around the numbers of anchor link should we have till we need to have anchor links show up on the right-hand side, let's find out. I will post the question on the Carbon Slack channel.

**Comment by JennySanchez** [comment]
Jacob, 

I shared my findings with the Carbon Team and based on the discussion on Slack and in-person with Anna, below are the basic rules when it comes to anchor link set up.

![Screen Shot 2020-02-18 at 4 19 34 PM](https://user-images.githubusercontent.com/45213839/75060071-cb928100-54a3-11ea-98c4-daab80090ad2.png)

- There should never be one link stand alone on the right-hand side by itself. 
- When it's an even number of links, for example, six links, we will have three links on the left-hand side and three links on the right-hand side.
- When it's an uneven number of links, for example, nine links, we will have five links on the left-hand side and four links on the right-hand side.

**Comment by JennySanchez** [comment]
**Next step:** Update cupcake site to newest Gatsby Theme#1445.
