### ISSUE TITLE
Review and get feedback for Cupcake website Homepage design

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#326]
#### User story
> As an IBM.com Library adopter, 

> I need to go to a website to get guidelines and resources  I need for my work without confusion 

> so that I can find the information I need with confidence.

#### Tasks
- [x] Review design options (#305) with Wonil and designers

#### Acceptance criteria
- [x] Feedback received and can move on with revision (if needed)

**Comment by JennySanchez** [comment]
**Purposed homepage design in two directions with three variations:**
![Screen Shot 2020-02-14 at 2 28 43 PM](https://user-images.githubusercontent.com/45213839/74567004-6afec380-4f3a-11ea-82b4-cbbc73c6a33f.png)
![Screen Shot 2020-02-14 at 2 56 45 PM](https://user-images.githubusercontent.com/45213839/74567012-6e924a80-4f3a-11ea-87a1-db6c64670ad5.png)

---

@jimpistilli Can you take a look at the proposal mockups in the folder (attached below) and let me know if you spot any typos? Thank you.
[Homepage redesign purposed ideas.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/4206849/Homepage.redesign.purposed.ideas.zip)

**Comment by jimpistilli** [comment]
@JennySanchez Sure will circle back shortly

**Comment by jimpistilli** [comment]
@JennySanchez Hi - some of the screen captures are not a high enough resolution for me to read all of the text, there are portions that are too small / blurry. Is there a way to send better quality versions? Thanks

cc: @wonilsuhibm

**Comment by jimpistilli** [comment]
@JennySanchez Below is a box link to a new zip file of the screens in PDF format, with some edits and questions.  Happy to discuss when you're free

https://ibm.box.com/s/0petoiwgouhifeb37brn2ounxr95ua8j

cc: @wonilsuhibm

**Comment by JennySanchez** [comment]
@jimpistilli Thank you for taking a look. Great questions and the items you have upper or lower case questions with, they are proper nouns, so they start with cap case. Each Cards also take adopters to different places to view information, download asset, etc. That's why the icons are different.

**Comment by jimpistilli** [comment]
@JennySanchez Got it, i will update w/a new version reflecting your comments. Thanks for looking

**Comment by JennySanchez** [comment]
Purposed homepage designs updated with feedback from Jim:

![Screen Shot 2020-02-20 at 4.01.57 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/4bd05ec6-5d1d-4455-9f24-f7f9e3ef74b2)![Screen Shot 2020-02-20 at 4.02.52 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/37c4c704-d5f9-4f6d-9d0f-1f5dc6f2e49a)

**Comment by jimpistilli** [comment]
New versions below, as per Jenny's comments on my questions

https://ibm.ent.box.com/file/618778770787

cc: @JennySanchez @wonilsuhibm

**Comment by JennySanchez** [comment]
@jimpistilli Got it and will update the purposed designs.

**Comment by JennySanchez** [comment]
@wonilsuhibm Let me know what do you think?

2x size designs are attached below.
[Homepage redesign purposed ideas 02.25.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/4251723/Homepage.redesign.purposed.ideas.02.25.zip)


<img width="929" alt="Screen Shot 2020-02-25 at 1 04 58 PM" src="https://user-images.githubusercontent.com/45213839/75278546-af5a5100-57cf-11ea-82cb-31011f7c1bf1.png">
<img width="839" alt="Screen Shot 2020-02-25 at 1 05 31 PM" src="https://user-images.githubusercontent.com/45213839/75278554-b2554180-57cf-11ea-9172-5d2b7a71704f.png">

**Comment by RobertaJHahn** [comment]
Closing this issue based on Jenny's notes above.
