### ISSUE TITLE
Create adopter requirement list

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#327]
Based on the discussion, we need to create guidance for our adopter groups to make sure they know what they need to do to adopt Carbon.

- Drupal adopter, leading them to the Drupal website for guidelines.
- The rest of the adopters, create a minimal requirement list to help them creating IBM.com pages and experience.

**Prior discussion detail can be viewed #311**

**Comment by JennySanchez** [comment]
@jimpistilli We talked about we need to craft the paragraph/message to be added to the Get Started/Overview page for adopters to find the information they need. I think I need to have the requirement list gathered before you can start. Please hold on and I will reach out when I have the detail.

**Comment by JennySanchez** [comment]
@jimpistilli Can you take a look at the content below and make any adjustments to make sure we are good to publish it on the website?

(Section title)
Various paths for the adoption of Carbon across IBM.com

(Content)
**For pages produced and published in the Marketing Platforms Drupal CMS, there is the Web Simplification path:** 
Carbon will be made available through the creation of web simplification templates. The use of these templates as they become available is the path to Carbon because these templates are part of a new content model and publishing tool and have been studied and researched for their overall effectiveness. For more information, details are provided here: https://w3.ibm.com/w3publisher/template-simplification

In the interim, while these templates are being designed and built-in CMS, page owners can use the Design Guidelines to configure existing pages to have the look and feel of IBM Design Language. Those Design Guidelines can be found here: https://w3.ibm.com/w3publisher/squad-pulse/marketing-platforms/drupal-cms#Links

**For websites or applications built using v18 (Northstar), v19a, or earlier, there is the IBMcom Library path:** 
This website explains how to get started with the IBMcom Library. It provides links to the code repository, the storybook, usage guidelines, and additional resources for getting started. Keep in mind the following things as you get started:

- Carbon and IBMcom Library is built using Node Package Manager (NPM), not the Content Delivery Network (CDN), so it requires a complete development rewrite, unlike prior design systems. 

- Carbon has a new 2x grid so everything needs to be designed understanding that grid.
- It is open-source, so any adopters are invited to contribute to the open-source IBMcom Library

To assist adopters through this transition, Digital Design squad can consult with a team as they are getting started or as they are ready for review. Reach out on our slack channel at #ibm-digital-design.

**Comment by jimpistilli** [comment]
![image](https://user-images.githubusercontent.com/32171262/75372068-e2671800-5895-11ea-9f6d-ad6cecc12846.png)

**Comment by jimpistilli** [comment]
@JennySanchez Please visit the box link for an updated version that has some minor edits and corrections:

https://ibm.box.com/s/gnepzc9e8zoc0yq5ep7rarepw23snopb

**Comment by JennySanchez** [comment]
Content published and the deploy preview can be viewed [here](https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/351/index.html).

**Comment by JennySanchez** [comment]
Content showing up on the live website and can be viewed [here](https://ibm-dotcom-library.mybluemix.net/getting-started).
