### ISSUE TITLE
Content edit for the CTA Guideline/Placement section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#353]
#### As-Is:

**Placement**
CTAs should be quickly identifiable, even if a reader is just scanning the page. Make them eye catching and easy for your reader to find. A CTA’s placement should also be located where it makes the most sense for the content structure of the page, and they should not be scattered throughout the page. Also note that while it’s important to place a CTA in an easily identifiable position, do not place them too early on the page, where a reader will be presented with the link before reading the objective your page.

#### Visual references:
![CTA Guideline v3 - reference](https://user-images.githubusercontent.com/45213839/75817572-f6f75480-5d5c-11ea-8255-39a85696924e.jpg)

**Comment by JennySanchez** [comment]
#### Feedback for edit:

"make them eye catching" is a little misleading because we would want teams to use the link and buttons styles that are in the system already, not change them to make them eye catching. Maybe we can say something like "make them prominent enough"...

instead of "they should not be scattered throughout the page" maybe we should say something like “the CTAs should help guide users through the content and can be placed strategically (or thoughtfully) throughout to drive users to the content or action they are trying to achieve”
This particular feedback is coming from the design for Lila’s learn page does have CTAs distributed throughout the page and “scattered” could be interpreted in layout or placement

"do not place them too early" could say something like: placing a CTA high on the page could distract/drive users somewhere else before they reach the main objective of your experience, consider where the primary actions should be placed and when the users are ready for them.

**Comment by jimpistilli** [comment]
@JennySanchez Draft attached that addresses the concerns above. Can discuss if you'd like:

https://ibm.box.com/s/3llinph7ipi42ux5xbht32a3gznr0tt7

**Comment by JennySanchez** [comment]
@jimpistilli We are good with this task. Thank you for taking care of the edits.
