### ISSUE TITLE
Follow up with the Carbon Team on component demo window implementation

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#373]
(Task created as one of the action items from the Gatsby Theme website building process retro #242).

> As a Cupcake website creator,

 > I need to know what we need to do to implementation and demo window feature to showcase the components

> So that we can be aligned with the carbon website and create a great browsing experience for our adopters.

---
@ljcarot 

Our previous discussion can be found via [#122](https://app.zenhub.com/workspaces/ibmcom-library-5d449f3642eb1962336cbe52/issues/carbon-design-system/ibm-dotcom-library-website/122)

We need to see if the demo window feature still is for the wedding cake before we reach out.

**Comment by JennySanchez** [comment]
**Update:** Followed up via a [Git issue](https://github.com/carbon-design-system/carbon-website/issues/870) on the Carbon Gatsby Github and his comment is as follows.

![Screen Shot 2020-06-24 at 10.26.40 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/f11dbb56-5dde-4f11-802a-cfd3926b768d)

---

![Screen Shot 2020-06-24 at 10.27.16 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/9ddfd63b-5245-4843-b1f6-db7356b825a0)

**FYI:** @jeffchew @wonilsuhibm

**Comment by JennySanchez** [comment]
**Update:** This task will be closed and the follow up with the Carbon Team will be done in Q4 - detail can be viewed #493.

Why?
- There's no movement on the demo window feature task on the Carbon side. 
- Based on the ideation cycle two discussion, the DDS leadership team also agreed on focus on the implementation plan around Q4.

**Comment by wonilsuhibm** [comment]
Thank you Jenny. Let’s keep this in our back pocket for now.
