### ISSUE TITLE
Create and update the Lead space page/Patterns in use section images (Part two)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#376]
(Part one work done by Jacob can be viewed via #165 )

> As a IBM.com Library website creator, 

> I need to create the Patterns in use section images to be displayed as a gallery layout with mockup style images,

> so that it looks more refined.

#### Additional information

- The v1.0 Lead space page can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/patterns/leadspace).

- Below are the examples of the Gallery style images provided by @larahanlon2 for references.![Screen Shot 2019-12-09 at 3.32.50 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/1e3f832d-0702-48b5-8928-ab69c4ad12d3)
![Screen Shot 2019-12-09 at 5.13.22 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/eb2f8127-6dbb-4075-b288-b5f4ba53b9ad)

#### Acceptance criteria
- [ ] Continue the Images created in Sketch app.
- [ ] Images and design reviewed with Wonil and Lara.

#### Acceptance criteria
- [ ] Images updated on the website.

**Comment by JennySanchez** [comment]
Work file from Jacob can be found [here](https://ibm.box.com/s/rbzpflvn926gqpw2mzinjr53j2jf79wa).

![Screen Shot 2020-03-27 at 11 49 13 AM](https://user-images.githubusercontent.com/45213839/77779944-46116c00-7021-11ea-9d6f-1541eb2d1a4c.png)

FYI - @larahanlon2 @wonilsuhibm

**Comment by JennySanchez** [comment]
@wonilsuhibm @larahanlon2 Below are three purposed directions for the "Pattern in use" section image treatment on the Lead Space page.

I include a zoom-out view for each direction so we can see how it looks like with other images on the page.

(Option A)
![Option A - laptop view.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d50b645a-b2d2-4040-b04c-b252d1e8108a)
![Screen Shot 2020-04-02 at 2.16.15 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/cb828316-c604-48f9-ba71-ec1cf5b8eaa4)

(Option B)
![Option B - phone view.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/06d7a45c-2f49-4c86-99c1-51678b995aa7)![Screen Shot 2020-04-02 at 2.47.08 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c4c2aa6d-4247-4ae8-a5d0-0b44abdeca8b)

(Option C)
![Option C - block view.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/4cb61be6-babc-4943-8aa6-04c3d8ce7e22)![Screen Shot 2020-04-02 at 2.17.38 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/65f5366c-1eb0-400c-b2fa-6563aa36aa2b)
---

@lara A few questions for you below.

1. Can I have the full image file for all the images but not just the lead space cut off an image? So I can make sure the option A works with the dimension I have.

2. Is "Lead space left-aligned used to introduce a visitor to AI." a good caption for the image below? This image we currently do not have is this one of the options for me to pick or this is something we need to add. 

**FYI:** I set up a quick call for us next Monday as a question follow up.

**Comment by JennySanchez** [comment]
@wonilsuhibm

I had a discussion with Lara about the Pattern in Use images today. We are moving forward with updating the images based on what we currently have in the Storybook.

The images will be mockup based on the actually built components but not what was collected back to December 2019. 

The Lead space page content will need an update as well but not a high priority at this moment. We will consider coming back to the image update when the content is ready.

**Comment by lara** [comment]
@JennySanchez you tagged the wrong person

**Comment by JennySanchez** [comment]
**Purposed images:**

![01](https://user-images.githubusercontent.com/45213839/79014244-176eb780-7b30-11ea-95af-e378778a407c.jpg)
![02](https://user-images.githubusercontent.com/45213839/79014250-1b9ad500-7b30-11ea-99b3-4c79e4264946.jpg)
![03](https://user-images.githubusercontent.com/45213839/79014251-1ccc0200-7b30-11ea-8b2d-4497d9041569.jpg)
![04](https://user-images.githubusercontent.com/45213839/79014252-1ccc0200-7b30-11ea-98c7-154e9e59b35b.jpg)

---


Images will be implemented and designed with the content update to align with ontology and dev refactor (#347).
