### ISSUE TITLE
Fix the bullet points to en-dashes on the Lead Space page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#378]
![Screen Shot 2020-04-02 at 1.51.44 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/ac6e6b96-2ba1-4ede-acc8-0f1c72688e8f)

#### Note: 

The chart is on the [Lead Space page](http://ibm-dotcom-library.mybluemix.net/patterns/leadspace/).

A while back, Jeff worked on the fix for the chart spacing after Jacob and I tried to fix it with the markdowns. This fix is in the same situation, a dev resource is required to make sure we can use the en dashes instead of the bullets.

**Comment by RobertaJHahn** [comment]
This should be fixed by the Gatsby team, rather than having our team override the bullet with a dash.

**Comment by JennySanchez** [comment]
Bug issue created on the Gatsby repo and can be viewed [here](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/809).

**Comment by JennySanchez** [comment]
After some research, we found out the table is not using a data table or structured list but a native markdown table. What we need to do is ask Vince how to use an unstructured list in the cell of a markdown table, or if we have to switch to a structured list table to have the en-dash styling works.

**Next step:** Add the findings to the bug issue opened on Gatsby repo.

**Comment by JennySanchez** [comment]
Reached out to Josefina, dev on the Carbon team,  today for follow up and make sure she does not need anything else from us.

**Comment by JennySanchez** [comment]
@jeffchew @wonilsuhibm 

Vince on the Carbon Team mentioned the Carbon Gatsby currently don't need the feature, if we want, we can work on it and he would welcome a PR. 

📍 I'd like to get your thoughts on this.

The bug does not impede the usability or functionality, but it's visible or noticeable to designers. It's a minor detail, but I would like to have it fix it at some point if we can not dedicate any resources to it for now.

📍Can I get a possible timeline as a placeholder for the fix?

**Comment by wonilsuhibm** [comment]
I think this is a relatively low priority item—I suggest that we add this as a feature request and submit a PR into Gatsby codebase when the dev team has the time, but not log this as a blocker for the upcoming release on April 26th.

**Comment by jeffchew** [comment]
@RobertaJHahn @JennySanchez would like to push this out to sprint 9,. don't think we can get to this this week.

**Comment by JennySanchez** [comment]
**Task update:** As discussed in the stand-up today, Jeff will post this task in the engineer/dev channel and see if there's a volunteer who can take up the task.

**Comment by JennySanchez** [comment]
@andysherman2121 Let me know if you have any questions.

**Comment by andysherman2121** [comment]
@JennySanchez Will do!

**Comment by JennySanchez** [comment]
@andysherman2121 How's the fix go and do you have any questions besides the ones we went over the last sprint?

**Comment by andysherman2121** [comment]
@JennySanchez Hey Jenny, still working on the fix. Hope to finish it today. Will take a while to implement because Gatsby has to adopt it first, then do a release, then we have to update our dependency. But no questions as of now!

**Comment by JennySanchez** [comment]
The fix looks great and PR approved. Thanks, @andysherman2121 !
