### ISSUE TITLE
Cupcake website footer content needs updates

### ISSUE THREAD

**Issue by wonilsuhibm** [carbon-design-system/ibm-dotcom-library-website#379]
@wonilsuhibm commented on [Mon Apr 06 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1974)

### User story
As a maker of IBM.com, I need to understand when to use the short version so that I don't misuse it.

### notes
- Currently the footer page states that the short version is available when the screen real estate is limited. This is incorrect. The language should be that the short version is only available to pre-approved transactional pages such as check-out and registration. All other pages should use the default version.

### Acceptance criteria
- [ ] The language on the page has been updated.

---

@wonilsuhibm commented on [Mon Apr 06 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1974#issuecomment-609942329)

There seem to be two Box notes, neither of which reflect the desired guidelines. As a part of this exercise, please archive as needed, and leave one master doc in [this folder](https://ibm.box.com/s/ks8juuduyzxf67nqrpxmpqy81fi0nsqp)

---

@wonilsuhibm commented on [Mon Apr 06 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/1974#issuecomment-609953557)

Here is a content update proposal from a while ago—this seems to have some of the correct information. Let's take this into consideration in the final update.

https://github.com/carbon-design-system/ibm-dotcom-library-website/issues/108#issuecomment-565157179

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm 
Which explains the minimal footer best?

## Option 1: Minimal footer variant reduces space by removing any additional navigation. This footer is reserved only for approved transactional pages such as check out and registration. All other pages should use the default footer.

## Option 2: Minimal footer variant removes the additional IBM navigation, this should be used in transactional experiences where the user is trying to complete a specific task, like registering for an IBM account.

## Option 3: The minimal footer removes all high-level corporate navigation, leaving the required legal links, locale selector and branding. The minimal footer is reserved for approved adopters only and is not recommended for general use on IBM.com.

## Option 4 (combination of all 3): The minimal footer removes all high-level corporate navigation, leaving the required legal links, locale selector and branding. This footer should only be used in transactional experiences where the user is trying to complete a specific task, like check out or registering for an IBM account. All other  IBM.com pages should use the default footer.

**Comment by jacobottesen-dgc** [comment]
Final copy based on Olivia, Wonil, & Jenny

"The minimal footer removes all high-level corporate navigation, leaving the required legal links, locale selector and branding. This is reserved for approved transactional pages only, such as check out and registration experiences. All other IBM.com pages should use the default footer."

Updated the cupcake site April 14th.

**Comment by jacobottesen-dgc** [comment]
@wonilsuhibm @JennySanchez @oliviaflory 

Footer content has been updated. Changes can be viewed here: http://ibm-dotcom-library.mybluemix.net/components/footer
