### ISSUE TITLE
Cupcake website page creation - Patterns/Cards page 

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#38]
_chsanche created the following on Sep 23:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the components, patterns, etc

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/476.
- Card page on v19a website Components section can be viewed [here](https://www.ibm.com/standards/web/components/card/).
- Tile page on the current Carbon Design website can be viewed [here](https://www.carbondesignsystem.com/components/tile/code)

#### Task
- Collaborate with Lara for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1750_

**Comment by JennySanchez** [comment]
**Update:** Reviewed the Card explorations we currently have with Wonil on Wednesday. He will do an audit of what we should include and come up with a list for us to filter through and move forward with the next step.

**Comment by JennySanchez** [comment]
@larahanlon2 Can you confirm "Card" will not be part of the Layout Pattern content for the future so we can either close or re-prioritize this task issue? Thank you.

**Comment by larahanlon2** [comment]
@JennySanchez I can confirm that `cards` as it has been identified in this issue and v19a site will not be part of the Layout Patterns in cupcake. However, we will have patterns _with_ cards but we are currently working out the details (naming, final development etc). 

I think we can **close this task** and open a new one that is much more specific when we know the next step.
