### ISSUE TITLE
IBM.com Style Model page content and IA discussion

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#389]
> As an IBM.com Library website creator, 

> I need to have alignment on what content will go into the uIBM.com Style Model page and how the reference link linking strategy will look like with Wonil

> so that I know how to move forward with the content crafting.

#### Additional information

The Mural.ly board used for discussion can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579113436354?sender=chsanche&key=26c3f47a-f226-44aa-bee7-223107a17b94).

#### Tasks
- [ ] Discuss with Wonil and find out details needed

#### Acceptance criteria
- [ ] Have a clear idea of what we will have and set up the IBM.com Style Model page.

**Comment by wonilsuhibm** [comment]
Issue moved to [carbon-design-system/digital-design-ideation #37](https://github.com/carbon-design-system/digital-design-ideation/issues/37) via [**ZenHub**](https://www.zenhub.com/)
