### ISSUE TITLE
Cupcake website page creation - Patterns/Page layout page

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/ibm-dotcom-library-website#39]
_chsanche created the following on Sep 24:_  

 

#### User Story

> As an IBM.com page creator

> I need to: have a good understanding of the page layout

> so that I can: do my day to day work without confusion.

#### Additional information
- Cupcake website page development priority can be viewed via https://github.com/carbon-design-system/ibm-dotcom-library/issues/482.
- Current Layout page on v19a website Components section can be viewed [here](https://www.ibm.com/standards/web/design-guidelines/layout.html).
- Layout page on Carbon website can be viewed [here](https://www.carbondesignsystem.com/guidelines/layout)

#### Task
- Collaborate with Lara for the content creation.

#### Acceptance criteria
- [ ] Content and design created and reviewed with the stream lead, the developer and Wonil.
- [ ] Shared with the Carbon and IDL team for feedback.
- [ ] Content and design accepted by Wonil and Linda.
- [ ] Create the dev. issue for coding as the next step.

 

_Original issue: https://github.ibm.com/webstandards/digital-design/issues/1757_

**Comment by JennySanchez** [comment]
**Note:** Peet on the IDL team shared the latest IDL Layout page and can be viewed [here](https://deploy-preview-344--design-language-website.netlify.com/design/language/elements/layout/overview/)

FYI - @larahanlon2 @wonilsuhibm

**Comment by RobertaJHahn** [comment]
This overview page has been created.  Closing this issue.
