### ISSUE TITLE
Cupcake website April release communication planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#397]
#### Task
We need to think about what we are going to share with adopters for the April release announcement.

---

@ljcarot @wonilsuhibm This task issue is created for you to discuss the announcement channels such as Slack channels, emails, etc. Please let me know if there's anything I can help you with and we should share the plan with the team before release. Thank you!

**Comment by JennySanchez** [comment]
**Draft from Linda:**

![Screen Shot 2020-04-24 at 3 40 22 PM](https://user-images.githubusercontent.com/45213839/80255177-09e22300-8642-11ea-92a5-56ae752bc7ef.png)

**Comment by JennySanchez** [comment]
Feedback from Roberta:
"now" in the third sentence. is it correct?

**Comment by ljcarot** [comment]
How about this...to be more clear...  'With this launch, we'd like to also expand the purpose of this channel to include questions related to IBM.com Library.'

**Comment by RobertaJHahn** [comment]
Cupcake website released April 24, 2020.  Closing this issue.
