### ISSUE TITLE
Cupcake website page creation - Homepage

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#40]
#### User Story

> As an IBM.com page creator

> I need to: know what is the Cupcake website about and see resource links on the homepage

> so that I can: get started without confusion.

#### Additional information
- IDL's homepage can be viewed [here](https://www.ibm.com/design/language/).
- Carbon's home page can be viewed [here](https://www.carbondesignsystem.com/).
- Current v19a website home page can be viewed [here](https://www.ibm.com/standards/web/).

#### Acceptance criteria
- [ ] Content and design published with markdowns.
- [ ] Content and design reviewed with Wonil and Mike.
- [ ] Content and design accepted by Wonil and Linda.

**Comment by JennySanchez** [comment]
@wonilsuhibm I asked about the video for the homepage today. If you know where we can find a selection of video for our homepage, please let me know. :-) Thank you!

**Comment by wonilsuhibm** [comment]
@JennySanchez Let's go with a still image as the MVP as we discussed, which is what Carbon did in the beginning too. Let me take some pictures here.

**Comment by JennySanchez** [comment]
@wonilsuhibm I was thinking the same thing. Do you have the link to the image library?

**Comment by jacobottesen-dgc** [comment]
Hey @jeffchew I was working on the Homepage and making edits and the deploy failed. Is there anyway you could go in and fix whatever is wrong?

https://github.com/carbon-design-system/carbon-for-ibm-website/pull/162

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Below is a homepage banner image I quickly put together for code testing and markdown set up.

Please note: 
- The image concept is to show an adopter working with the Design Kit or browsing the Carbon for IBM.com website.
- The mockup image is from the IDL image library and will be replaced later.

![0100041_Oppemann_PE_edit](https://user-images.githubusercontent.com/45213839/70580181-78818100-1b78-11ea-87d0-f96abe959fa2.jpg)

FYI - @wonilsuhibm

**Comment by JennySanchez** [comment]
@wonilsuh we need help with a paragraph for the homepage.

This is what we currently have:
"Carbon for IBM.com is an open source design system for IBM online experiences. It is for the community of designers, developers, and anyone involved in the making of marketing and editorial experiences on IBM.com."

**Problem:**
- It's not open source.
- Jeff brought up a good point: There will be folks that are using the IBM.com Library that isn't necessarily making a marketing/editorial experience. For example, registration and URX would be using our footer and header, but I think are using the productive carbon theme

**Comment by wonilsuhibm** [comment]
The whole paragraph feels written for a truly open source design system that anyone can adopt and build their own design system. We are only for IBM. URX is using the productive theme at the moment, but will switch to the expressive theme. 

But Jeff does bring up a good point - not all experiences on IBM.com are editorial or marketing (in the narrower sense of the word). Let's rewrite it. How about this?

```
Carbon for IBM.com is a collection of components, patterns, tools, and guidelines for designers and developers building IBM.com experiences. Its components and patterns are based on Carbon Design System and optimized for building IBM.com experiences.
```

What do you guys think?

**Comment by jeffchew** [comment]
> "Carbon for IBM.com is a collection of components, patterns, tools, and guidelines for designers and developers building IBM.com experiences. Its components and patterns are based on Carbon Design System and optimized for building IBM.com experiences."

I like it. Adding @ljcarot for feedback as well.

**Comment by ljcarot** [comment]
I agree. I like it!

**Comment by JennySanchez** [comment]
I like the copy as well. We will add this to the homepage. Thanks everyone!

**Comment by JennySanchez** [comment]
Homepage "Carbon for IBM.com " section copy completed and can be viewed on [Homepage](https://carbon-for-ibmdotcom.netlify.com/).

**Comment by JennySanchez** [comment]
@wonilsuhibm I need your feedback on the following image selections for the [Homepage](https://ibm-dotcom-library.netlify.com/). I would like to try the illustrations you created in the past as well, if you have anything, please share with me.

#### Designing

![Screen Shot 2019-12-17 at 3 47 47 PM](https://user-images.githubusercontent.com/45213839/71037177-cd774700-20e4-11ea-88e3-62fd978f3dab.png)

#### Developing
![Screen Shot 2019-12-17 at 3 47 55 PM](https://user-images.githubusercontent.com/45213839/71037185-cf410a80-20e4-11ea-9da7-87efdbf10954.png)

#### Latest news
- It should be "Latest updates".
- Once the images are in place, the contrast will be adjusted.

![Screen Shot 2019-12-17 at 4 00 22 PM](https://user-images.githubusercontent.com/45213839/71037950-5f338400-20e6-11ea-9552-51c062158dcb.png)

**Comment by JennySanchez** [comment]
@wonilsuhibm Round two images options for the Latest updates section.

FYI: Slack logo usage is following the Slack logo [usage guideline](https://a.slack-edge.com/0f43e/marketing/img/media-kit/Slack-Brand-Guidelines.pdf).

![Screen Shot 2019-12-18 at 9 50 33 AM](https://user-images.githubusercontent.com/45213839/71102173-a28d0180-217d-11ea-809d-71de73a65f33.png)

**Comment by JennySanchez** [comment]
**Update:** Received feedback from Mike and will work on the edits.

**Comment by JennySanchez** [comment]
**Where I left yesterday:**
![Screen Shot 2019-12-18 at 8 18 04 PM](https://user-images.githubusercontent.com/45213839/71193126-324eb080-224f-11ea-829b-e63c32b77ce4.png)

**Comment by JennySanchez** [comment]
Based on the discussion...

- [ ] Jenny will export the images for the "Latest updates" section and have it ready for Jeff to work on the image upload.
- [ ] Jenny will share the work file with Wonil and Jacob for hero image exploration.
- [ ] Jenny and Wonil will keep going with the image exploration on the "Getting started" section.
- [ ] Wonil will provide hero image options for final selection by EOD today
- [ ] Jeff agreed on uploading the hero image tomorrow morning

---

Latest Homepage work file can be found on website [BOX folder](https://ibm.box.com/s/r1lgx1psxyeru8l31mfodjwzb4y65w5h).
![Screen Shot 2019-12-19 at 2 07 01 PM](https://user-images.githubusercontent.com/45213839/71206424-21f7ff00-226a-11ea-9552-bbba29638438.png)

**Comment by JennySanchez** [comment]
**Latest update section images:**
(Image size)
![Screen Shot 2019-12-19 at 3 12 06 PM](https://user-images.githubusercontent.com/45213839/71209797-10b2f080-2272-11ea-9de1-36285b6bee7c.png)
![Screen Shot 2019-12-19 at 3 11 17 PM](https://user-images.githubusercontent.com/45213839/71209821-1e687600-2272-11ea-9835-069b0d11586a.png)
[Updated footer and masthead images.sketch.zip](https://github.com/carbon-design-system/ibm-dotcom-library-website/files/3985662/Updated.footer.and.masthead.images.sketch.zip)

**Comment by JennySanchez** [comment]
**Final Homepage design for the v1.0.0:**

![Homepage - Final](https://user-images.githubusercontent.com/45213839/71293582-80d97900-233b-11ea-82b8-f16476078e21.jpg)

---

- Homepage work file (IBM.com_library_website-Homepage_design-v2) can be found in the [BOX folder](https://ibm.box.com/s/gs0apv3kyopoiy72o3gphefbdm0op8xx).

- Homepage images can be found in the [BOX folder](https://ibm.box.com/s/qdzq46dltdift9j94lvktesjbdryt36y)
