### ISSUE TITLE
Add "What happened to the expressive theme?" to the FAQ page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#418]
The update came from the [April 24th release audit](https://ibm.box.com/s/fgizf8lp8vyo4jszpt8o3g7mq5k9akyu).

We need to address what happened to the expressive theme, so our adopters know why the expressive theme is no longer available to them.

**Comment by RobertaJHahn** [comment]
@JennySanchez Maybe we can close this issue and open a new one to create a page that explains to adopters what is available in expressive?

**Comment by JennySanchez** [comment]
@RobertaJHahn Before we know if we need a new individual page to explain what is available in the expressive theme, I need to know what will be available first so we can see if it makes sense to present the information within an existed website page or we need to create a new individual page and which category it will be under.

**Comment by RobertaJHahn** [comment]
@JennySanchez I'll close this issue and the work to include the Expressive theme content on the website will be managed under another issue.  As I mentioned in our Slack chat, Jeff volunteered to create an initial draft of the content.  Thanks Jenny
