### ISSUE TITLE
Adopter research planning for the Help/FAQ page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#42]
#### User Story

> As a Cupcake website content creator

> I need to: know what frequently asked questions our adopters have

> so that I can: consolidate them and present them on the FAQ page.

#### Additional information
- Let's talk to ~~Ashley~~ Penny if she has any tips on how we can conduct this research.

#### Acceptance criteria
- [ ] A plan with action items ready for the content collection.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Let's talk about how we are going to collect user feedback as the starting point. Can you set up something for us and Ashley to chat soon? Thanks.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez 

Here are some ideas for research methods:

– Survey
– Competitive research (review other FAQs from design systems)
– Interviews

Questions:

– After reviewing the site, what questions are still unanswered?
– What are the top 3 questions you have based on your review of the site?

Articles for inspiration:

https://publication.design.systems/building-successful-design-systems-with-a-well-integrated-research-550dd463039a

https://medium.com/elisa-design/maintaining-design-systems-with-user-research-3ba5feafc336

**Comment by JennySanchez** [comment]
@jacobottesen-dgc Great ideas and let's share them with Penny and get her input when we meet with her. 

For the competitive research (review other FAQs from design systems), one thing to keep in mind is our adopter has a very particular needs for creating IBM.com pages. The FAQ page content will need to tailor to their needs.

**Comment by JennySanchez** [comment]
Meeting scheduled with Penny on 01-09.

@jacobottesen-dgc 
Let's go over the following directions with Penny and finalize our plan for the next step.

- [ ] Box note feedback collection (near term)
- [ ] Survey (near term)
- [ ] Interviews (near term)
- [ ] Slack channel (long term)
- [ ] Hotjar Survey (long term)

**Comment by jacobottesen-dgc** [comment]
Met with Penny today. 

Got some greta advice from her about the FAQ page.

###Tips

- Use pop up Poll/surveys 
- (Keep it to 2 questions with contact info)
- Limit the site to 1 poll at a time

**Comment by JennySanchez** [comment]
**Next step:** Set up the Hotjar Survey (#260).
