### ISSUE TITLE
Add the Vanilla package to Get started/Coding Page if it's ready

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#420]
The update came from the [April 24th release audit](https://ibm.box.com/s/fgizf8lp8vyo4jszpt8o3g7mq5k9akyu).

Add the Vanilla package to Get started - [Coding Page](https://ibm-dotcom-library.mybluemix.net/getting-started/coding) if it's ready.

**Comment by JennySanchez** [comment]
@jeffchew Any updates on if the Vanilla package is ready?

**Comment by JennySanchez** [comment]
Followed up from Jeff - we will hold on the update to the Get started page. The DDS leadership team will need to discuss the fate of the Vanilla package today.

**Comment by jeffchew** [comment]
We are no longer investing in the vanilla package. We should begin to highlight the `Web Components` package.

Also I saw some other designs, we have no plans on supporting `Angular` or `Vue.js` for the foreseeable future, so those frameworks should not be included.

**Comment by JennySanchez** [comment]
@RobertaJHahn Based on Jeff's comment, we can close this task issue and open a new issue for updating the development documentation across the website.
