### ISSUE TITLE
Set up 404-page links and trigger

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#443]
During the audit, we discover the links on the 404-page is not set up with the correct labels and links (see below).
![Screen Shot 2020-04-24 at 2.08.24 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/0c5cab50-7679-43fd-b448-443601124038)

The label is updated but for some reason, the links are not working and need dev assistance.
![Screen Shot 2020-04-24 at 2.20.20 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/c711e83d-2647-4fc9-bcbf-e95c7b5d1c5b)

---

Help - https://ibm-dotcom-library.mybluemix.net/help
Slack - https://cognitive-app.slack.com/archives/C2PLX8GQ6
Github repo - https://github.com/carbon-design-system/ibm-dotcom-library/issues/new/choose

---
#### Task

- [ ] Link the Help, Slack, and Github repo to its proper pages.
- [ ] Figure out how to trigger the 404 on [mybluemix.net](https://cloud.ibm.com/docs), so all errors can be linked to the 404-page.

**Comment by JennySanchez** [comment]
@jeffchew Let me know which dev will work on the task, please. Thank you.

**Comment by JennySanchez** [comment]
@jeffchew Any update on this task?

**Comment by JennySanchez** [comment]
**Followed up with Jeff via Slack on 06/25.**

Per Jeff: 
I think it might involve webmaster team as they handle the overall 404 behavior on ibm.com. How important is it for us to have our own custom 404?

From Jenny:
The 404-error page is on our website but not for general IBM.com. It's in the Gatsby Theme. I updated the link label but the link (URL) is not working/connecting, so the task issue is created for the dev assistant around that - FYI.
The 404-error page is important  because as we have more traffic on the IBM.com Libray website and was presented with the 404-error page, they won't be stocked on that page.
also, tina williams owns the main 404 page

**Comment by JennySanchez** [comment]
@jeffchew Please let me know if my comment above makes sense.

**Comment by jeffchew** [comment]
Reached out to webmaster team, haven't received a definitive answer on this yet but they pretty much own how redirects work, especially for the standard 404 behavior and we would need to find the appropriate way of bypassing it on the EI server. Even then, we might need approval from them for this change.

**Comment by JennySanchez** [comment]
@jeffchew Thank you for the info. I'd like to keep this task open so we can keep an eye on it and continually record the progress. Please feel free to reach out if you have any further info from the webmaster team.

**Comment by JennySanchez** [comment]
@RobertaJHahn Can we update the milestone to Sprint 20-14? Thank you.

**Comment by RobertaJHahn** [comment]
@JennySanchez Done

**Comment by JennySanchez** [comment]
@jeffchew Any updates from the Webmaster Team?

**Comment by RobertaJHahn** [comment]
7/23/2020:

- The 404 page is a standard Gatsby page.  Jenny is asking to have several links added to the page.  (Help, Slack, Github Repo)
   - [Link to the DDS website 404](https://www.ibm.com/standards/web/ibm-dotcom-library/404/)
   - [Link to the Carbon 404 page](https://www.carbondesignsystem.com/404/)
       - The Carbon page works because they are hosted outside of IBM.  DDS website is hosted on EI.  
       - We must work with the webmaster team to get Akami configured
2)  Can we run a link checker on the website to identify the broken links on the site to be fixed?  

More discussion is needed to define the next steps.

**Comment by RobertaJHahn** [comment]
7/23/2020 Slack message from Jeff:

![image.png](https://images.zenhubusercontent.com/5d8b794c2134370001ce8d1a/6b533c68-0898-48cd-9aad-90953f08b70f)

**Comment by JennySanchez** [comment]
Task PR can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/584).
