### ISSUE TITLE
Planning - Tool for collecting user feedback on the website

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#453]
> As an IBM.com Library website content creator, 

> I need a way to collect adopter feedback

> so that I can resolve adopter pain points and make improvements to the Cupcake website.

#### Additional information
- Linda mentioned we no longer can use Hotjar to get feedback from the adopters on the website. Detail can be viewed [here](https://hub.webmaster.ibm.com/mac/hotjar-compliance/). The pop-up survey will be disabled, so we need to figure out a new tool for collecting user feedback.

#### Acceptance criteria
- [x] A possible solution in place for testing or implementation if needed.

**Comment by ljcarot** [comment]
To be clear, we are still collecting traffic. Its the pop-up survey from Hotjar that we had to disable.

**Comment by JennySanchez** [comment]
Note: The Carbon Team is using [Fathom](https://app.usefathom.com/share/vmsgxqrs/carbondesignsystem.com#/?from=2020-04-21%2000%3A00%3A00&site=2285&to=2020-04-28%2023%3A59%3A59) to collect data on the Carob Website.

![Screen Shot 2020-04-28 at 4 00 49 PM](https://user-images.githubusercontent.com/45213839/80537316-73776f80-8969-11ea-97ac-7ad7442b90fc.png)

**Comment by JennySanchez** [comment]
Hi, @ljcarot I know you reached out to Abhishek on Apr 28 about the Hotjar survey question since our audiences are the internal audiences. Did you hear anything back from him?

**Comment by JennySanchez** [comment]
Based on the discussion with Linda during the standup today. The Hotjar is back on the Cupcake website since our audiences are internal.
