### ISSUE TITLE
Initial QA for the IBM.com Library website White Theme homepage design

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#473]
@JennySanchez commented on [Thu May 28 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2578)

### Objective

To support Anna and help her complete the White Theme homepage design update for IBM.com Library website, we need to take a look at each section and create a list of items for tweaking or fixing.

#### Additional information
- Related Ticket(s)

Gatsby homepage code review for the new white theme design - Leads pace/hero image section #381
Gatsby homepage code review for the new white theme design - Get started section #382
Gatsby homepage code review for the new white theme design - Other resources section #383
Gatsby homepage code review for the new white theme design - Latest updates section #384
Gatsby homepage code review for the new white theme design - Contribute section #385

- Staging website for QA can be viewed [here](https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/472/index.html).

#### Acceptance criteria
- [x] Take a look at the new homepage together (Anna and Jenny)
- [x] Create a list of items for tweaking or fixing based on the initial QA outcome.
- [x] Create task issues (if needed) for tweaking or fixing based on the initial QA outcome.

**Comment by JennySanchez** [comment]
@annawen1 Great job and just a few items listed below for you to take a look. Let me know if you have any questions.

#### Overall

- [ ] The vertical spacing for the "Get started" and "Contribute" sections needs adjustment. As mentioned in our review session. The band will have 48 px on the top and 80 px in the bottom (see screenshot below for reference).

![Screen Shot 2020-05-29 at 8.33.29 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/629ff29b-226f-48dd-8efa-ed884ad02fc7)![Screen Shot 2020-05-29 at 8.33.44 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/d2d24dd2-ccbb-4855-8501-b310dd7c311d)


#### Other Resource

- [ ] For the IBM.com Pattern Library React card, we will link it to the Storybook page.
https://ibmdotcom-react.mybluemix.net/?path=/story/overview-get-started--default

#### Contribute
- [ ]  For the "Start contributing" CTA, let's link it to our Contrbution page.
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/472/contributions

---

Items need an update and will be provided by Jenny (work will be done via #467
- Hero image
(desktop) 2095 px by 749 px
(tablet) 610 px by 218 px
(mobile) 286 px by 189 px

- Illustration for the "Get Started" section.
(desktop) 287 px by 230 px
(tablet) 208 px by 171 px
(mobile) 287 px by 230 px

- Pictogram for the "Join Slack community" in the "Latest updates" section.
The pictogram stroke needs to be thinner

**Comment by JennySanchez** [comment]
@annawen1 Can you take a look at the Slack pictogram as discussed? Let's make sure the one you have is the latest before I make any changes. Sounds good?

**Comment by annawen1** [comment]
@JennySanchez for

> #### Contribute
> - [ ]  For the "Start contributing" CTA, let's link it to our Contrbution page.
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/472/contributions

do you mean this link instead?:  [https://www.ibm.com/standards/web/ibm-dotcom-library/contributions](https://www.ibm.com/standards/web/ibm-dotcom-library/contributions)

**Comment by JennySanchez** [comment]
@annawen1 Yes. :-)

**Comment by JennySanchez** [comment]
**FYI:** @annawen1 I reserved 30 minutes tomorrow (06/16 10:30 CST) for us to look at the approved final images and make sure you have what you need for the update.

**Comment by JennySanchez** [comment]
@annawen1 Below are the changes and items we went over today. Please take a look and let me know if I missed anything or if you have any questions.

- Hero message will be updated to:
"Our vision is that every visitor to IBM.com has a productive, efficient and delightful experience."
- Hero image will be updated to the one shown in the mockup below.
- Get Started section copy will be updated to:
"We have prepared a set of building blocks, tools and guidelines to help you to make this shared vision a reality."
- Get Started section image will be updated to the one shown in the mockup below and the image right hand-side edge will be touching the edge of the page. 

The Sketch work file can be found [here](https://ibm.box.com/s/1cv2hfk7u2ynf36s530qbl5nebwiox0f). The Sketch file has the spacer and grid set up for reference.
![Screen Shot 2020-06-16 at 11.06.18 AM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/dfff958a-f452-4bf8-a2c4-098c71547021)

The testing images can be found [here](https://ibm.box.com/s/lv3p826s6txw0bpvizrhaqb3pyb3u9xi).

**Comment by JennySanchez** [comment]
@annawen1 The images for the Get Started section can be found [here](https://ibm.box.com/s/lv3p826s6txw0bpvizrhaqb3pyb3u9xi). The sizes are based on the dimension you provided in our huddle today (Desktop: 338 px by 268 px, Tablet: 319 px by 253 px, Mobile: 338 px by 268 px). 

Let me know if you need anything else. Thank you.🙏

**Comment by JennySanchez** [comment]
@annawen1 My apology, I miss the "Productive" in the hero message should be set in Bold. Mockup updated.

**Comment by JennySanchez** [comment]
White Theme homepage update completed and the new staging link is ready.
https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/472

**Comment by ljcarot** [comment]
Looks very nice!

**Comment by wonilsuhibm** [comment]
Thank you. Looks great!!!

**Comment by JennySanchez** [comment]
Hi @ljcarot @jeffchew @wonilsuhibm 

The White Theme Hompeage update is completed. The PR for the update can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/472) and the preview site URL can be found [here](https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/472/index.html). Please let Anna and I know if you have a release day in mind, so we can push the update to go live on the website.

Reminder: We need to make an announcement on Slack for the update.


---

**FYI:** @annawen1

**Comment by wonilsuhibm** [comment]
@JennySanchez Thank you.

One thing—one a large monitor screen, the text wraps to four lines and results in a widow. This is generally considered a bad practice and if we can avoid it we should since we are the design standards team. I know this kind of thing is difficult to control on a live HTML page, but I'm asking because up to max size, the text stays in 3 lines, then suddenly wraps to four lines causing this issue. I'm not understanding why this is happening.

**Comment by annawen1** [comment]
> @JennySanchez Thank you.
> 
> One thing—one a large monitor screen, the text wraps to four lines and results in a widow. This is generally considered a bad practice and if we can avoid it we should since we are the design standards team. I know this kind of thing is difficult to control on a live HTML page, but I'm asking because up to max size, the text stays in 3 lines, then suddenly wraps to four lines causing this issue. I'm not understanding why this is happening.
> 
> <img alt="Screen Shot 2020-06-22 at 5 48 01 PM" width="1002" src="https://user-images.githubusercontent.com/30183447/85338566-8792a580-b4b0-11ea-99d0-98461c2a6997.png">

@wonilsuhibm I pushed the latest changes, if you take a look again the text should stay on three lines now on larger screens

**Comment by JennySanchez** [comment]
@annawen1 @wonilsuhibm Yes, set max-width to the Hero Message so it always stays with a minimum of three lines of text is one of the fix items. Let's use #477 for QA fix items updates.
