### ISSUE TITLE
Cupcake website - Content review (group two)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#48]
As a Cupcake website content creator, I need to collaborate with a content designer to make sure the content on the website meets our user needs, has a consistent voice and tone across the website, and with no typos.

For Sprint 23, we will collaborate on the following tasks:

- Publish approved content with markdowns (group two) #36 

- Review and approve content for Contribution/Overview page #35

**Comment by JennySanchez** [comment]
@RobertaJHahn FYI, the story points are reduced because we have a fewer page for Jim to review for this task.

**Comment by JennySanchez** [comment]
@jimpistilli We need a few items done before you can review the final content. We might need to move this task to Sprint 24.

@RobertaJHahn Sprint 23 ends tomorrow. Please change the Milestone label to Sprint 24.

**Comment by jimpistilli** [comment]
@JennySanchez Standing by

**Comment by RobertaJHahn** [comment]
@JennySanchez This issue is moved to sprint 24

**Comment by JennySanchez** [comment]
@jimpistilli Please start taking a look at the website as a whole and making the QA list - focus on Typo, weird paragraph, and general content edits. Thank you.

**Comment by jimpistilli** [comment]
Uploading each page as I review to the folder here:

https://ibm.ent.box.com/folder/96909803794

cc: @JennySanchez @jacobottesen-dgc

**Comment by jimpistilli** [comment]
All pages reviewed and suggested edits in PDFS in the folder below: https://ibm.ent.box.com/folder/96909803794

cc: @JennySanchez @jacobottesen-dgc @wonilsuhibm

**Comment by JennySanchez** [comment]
Got it. Thanks, @jimpistilli . I will take a look and let you know if I have questions.

**Comment by JennySanchez** [comment]
Review work from Jim is completed and the task issue will be moved to the Done column.
