### ISSUE TITLE
Update list and create descriptions for the Components and Layout Patterns list on overview pages

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#484]
#### Objective 

Our current Components and Layout Patterns overview pages do not reflect what we are offering via the Storybook. We need to make updates to make sure the adopters know what we are offering so that they can adopt.

#### Task

- Update the list and links on the Components and Layout Pattern overview pages.
- Create the list description for the Components and Layout Pattern list items.
- Review the update with Olivia and Lara.

#### Acceptance criteria

- [x] The list and description are updated and live on the Cupcake website

**Comment by JennySanchez** [comment]
**FYI:** @oliviaflory @jacobottesen-dgc

**Comment by JennySanchez** [comment]
**Task update:** The list on both overview pages is updated and will work on the list description next.

**Comment by JennySanchez** [comment]
**Task update:**

- List update completed.
- The list description work document can be viewed [here](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0).

**Comment by JennySanchez** [comment]
@larahanlon2 The Layout Patterns list description is ready for view and feedback and can be found [here](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0).

@oliviaflory The Components list description is ready for view and feedback and can be found [here](https://ibm.box.com/s/kome1qn15bklgydorkymbc3eqz9s0k2z).

Please feel free to make any edits and let me know if you have any questions. 

---

**FYI:** 

- The list on both overview pages is composed based on the list in [Storybook](https://ibmdotcom-react.mybluemix.net/?path=/docs/overview-getting-started--page). 
- Our goal is to make the update with the finalized description on the website by next Tuesday. 
- The description will also be added to the storybook DOC tab and used as the Intro section copy when we are crafting content for its pages.

**Comment by JennySanchez** [comment]
Status update: Description added to the website. Preview can be found inside of the [PR 507](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/507).

The Layout Patterns list description can be viewed [here](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0).

The Components list description ican be viewed [here](https://ibm.box.com/s/kome1qn15bklgydorkymbc3eqz9s0k2z).

**Comment by JennySanchez** [comment]
FYI: @ljcarot

**Comment by JennySanchez** [comment]
Description is live on the Cupcake website.

**Comment by ljcarot** [comment]
Thank you all for the hard work and last minute push to get these pages live!
