### ISSUE TITLE
Create wireframe images for the list items on the Components and Layout Patterns overview pages

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#488]
### Tasks

- Create wireframe images for available Components and Layout Patterns on the current overview pages.
- Review the images with Wonil and stream leads for feedback.
- Finalize the images and have them ready for the website update.

### Acceptance criteria
- [ ] All listed components and layout patterns have a wireframe image for representation.

**Comment by JennySanchez** [comment]
@jacobottesen-dgc The set up on the Carbon website [Components Overview page](https://www.carbondesignsystem.com/components/overview) will be our reference and goal.

![Screenshot_2020-06-30 Overview – Carbon Design System.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/cd2fa53c-78dd-45e8-ba36-06d2ae148b57)

**Comment by jacobottesen-dgc** [comment]
Meeting with Jenny on July 6th to review a few wireframe designs. 

![Screen Shot 2020-07-06 at 8.34.19 AM.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/a116697d-317d-4c1d-8b81-3b769b2fe838)

**Comment by wonilsuhibm** [comment]
<img width="588" alt="Screen Shot 2020-07-07 at 9 11 53 AM" src="https://user-images.githubusercontent.com/30183447/86798590-ef172c00-c03e-11ea-8f1e-983f072d21c9.png">

Testing

**Comment by jacobottesen-dgc** [comment]
@JennySanchez I've finished all the components, would you mind reviewing these for visual feedback?

![ComponentWireframes.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/33a95441-4b47-4b5b-b66f-cdeafaabaafa)

**Comment by JennySanchez** [comment]
Thank you, @jacobottesen-dgc 

Let me know if you have any questions after taking a look at the few things shared below.

- For the "Call out", I think the gray background is not part of it. 
- For the "Card group" is incorrect. It should look like a group of cards. It currently looks exactly like the Button Group above. 
- For the "Content item horizontal", maybe update the second link to be a different action icon? Right now it has two exactly same sets of CTAs and it looks like it's a mistake. See Storybook for reference [here](https://ibmdotcom-react.mybluemix.net/?path=/story/components-contentitemhorizontal--default).
- For the "Feature card", should the arrow in Blue 60?
- For the "Image" it looks accurate but I wonder if there's something else we can do to make it more interesting? Instead of a gray square? What do you think?
- For the "Link list", (If it's the default version) I believe there's dividing line in between each link. See Storybook for reference [here](https://ibmdotcom-react.mybluemix.net/?path=/story/components-linklist--default).
- For the "Local modal", are the CTA arrows missing? See Storybook for reference [here](https://ibmdotcom-react.mybluemix.net/?path=/story/components-locale-modal--default).

**Comment by jacobottesen-dgc** [comment]
Finished all wireframes for components and pattern. Waiting for review/approval from design team

![OptionB.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/4acf5b8e-97db-4f91-a6e7-5a90e7cf4bc5)

![ComponentWireframes.png](https://images.zenhubusercontent.com/5da5ed9833f74500019c499f/5e202758-b639-4979-a3b4-c149a775ec4e)

**Comment by jacobottesen-dgc** [comment]
View all wireframes images in sketch file: https://ibm.box.com/s/7gvawiosegrq99gkdauxvvem81ls7poy
