### ISSUE TITLE
Content crafting - Expressive theme proxy 

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#494]
📍 This task is a placeholder. Detail will be added when Expressive theme proxy documentation and design kit are in work.📍

#### Objective

We need to surf the Expressive theme proxy information on the website so IBM.com Library adopters know how to adopter.

#### Tasks
(TBD)

### Acceptance criteria

- [ ] Expressive theme proxy information is finalized and ready to be published on the Cupcake website.

**Comment by RobertaJHahn** [comment]
Content for this page has been crafted by Jeff and Wonil.  Closing this issue.
