### ISSUE TITLE
Content Publishing - Pattern (05 CTA Section)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#504]
#### User Story

> As an IBM.com Library pattern adopter, 

> I need a way to learn more about the (Name of the Pattern here) pattern 

> so that I can utilize the pattern to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the pattern works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/dgmmw2kpvtt3hpw8bazprawpfxfvsac3) to your machine to make the updates. Name the Sketch file with the following convention: Name of the pattern + version. ex: `Feature card block v1.0`
- Use the pattern description included in the [Patterns Overview Box Note](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0) - for the 'Intro' section of the newly downloaded Sketch file
- Navigate to the visual spec file within this [Patterns Box folder](https://ibm.box.com/s/dfmbd79ek0hmexfz1avg595njmzb2bap) - The image that works successfully for most patterns is the 1312px image.  Adjustments may be needed to have this image accurately reflect the Storybook designs.
- Once complete, save the revised Sketch file in the Layout Pattern folder / sub-folder [here](https://ibm.box.com/s/jao6qplwburqkn1vjrrrvxum1qn3dsoc).
- Export the individual images with a 2X setting, saving them into the Layout Pattern sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing
 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny as a PR Reviewer and Approver.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done.
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by JennySanchez** [comment]
**CTA section**

👉 Work files can be found in the [CTA section BOX folder](https://ibm.box.com/s/qgpmx9jkp00h72yqw3tavbh8rk6w9ncq).
![Pattern - CTA section.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/befc9582-3599-4df7-bd97-2e91f3abab5b)

**Comment by JennySanchez** [comment]
@ljcarot @wonilsuhibm @jeffchew 

Content markdown completed and the preview link can be found in [PR #546](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/546

**Comment by wonilsuhibm** [comment]
@JennySanchez This looks good. Thank you!
