### ISSUE TITLE
Content Publishing - Pattern (07 Callout  - Quote)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#506]
#### User Story

> As an IBM.com Library pattern adopter, 

> I need a way to learn more about the (Name of the Pattern here) pattern 

> so that I can utilize the pattern to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the pattern works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/dgmmw2kpvtt3hpw8bazprawpfxfvsac3) to your machine to make the updates. Name the Sketch file with the following convention: Name of the pattern + version. ex: `Feature card block v1.0`
- Use the pattern description included in the [Patterns Overview Box Note](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0) - for the 'Intro' section of the newly downloaded Sketch file
- Navigate to the visual spec file within this [Patterns Box folder](https://ibm.box.com/s/dfmbd79ek0hmexfz1avg595njmzb2bap) - The image that works successfully for most patterns is the 1312px image.  Adjustments may be needed to have this image accurately reflect the Storybook designs.
- Once complete, save the revised Sketch file in the Layout Pattern folder / sub-folder [here](https://ibm.box.com/s/jao6qplwburqkn1vjrrrvxum1qn3dsoc).
- Export the individual images with a 2X setting, saving them into the Layout Pattern sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing
 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny as a PR Reviewer and Approver.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done.
- [x] Publishing with markdowns is done.
- [x] QA'd by Jenny
- [x] Web page preview is approved by Linda, Jeff and Wonil
- [x] Web page is published

**Comment by JennySanchez** [comment]
**Callout quote**

👉 Work files can be found in the [Callout quote BOX folder](https://ibm.box.com/s/nhbihfrxyn7vk2ccsw8uz4bshb7ktacc).
![Pattern - Callout quote.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/2c5c6dfb-147c-4a8c-84c2-3a3efeb3a524)

**Comment by JennySanchez** [comment]
Markdown publishing completed and the PR detail can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/529).

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew @wonilsuhibm The page is ready for review. Thank you.

**Comment by wonilsuhibm** [comment]
@JennySanchez thank you. Please address use the em dash and sentence case for the pattern names in the doc. Otherwise, this looks good.

**Comment by JennySanchez** [comment]
The page is live and we did update the sentence case and use the em-dash between the design intent and attribute. Jacob and I did a huge batched update and it's not reflected in this PR and not yet on the website, FYI.

**Comment by wonilsuhibm** [comment]
Thank you!!!
