### ISSUE TITLE
Content Publishing - Pattern (08 Callout - with media)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#515]
#### User Story

> As an IBM.com Library pattern adopter, 

> I need a way to learn more about the (Name of the Pattern here) pattern 

> so that I can utilize the pattern to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the pattern works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/dgmmw2kpvtt3hpw8bazprawpfxfvsac3) to your machine to make the updates. Name the Sketch file with the following convention: Name of the pattern + version. ex: `Feature card block v1.0`
- Use the pattern description included in the [Patterns Overview Box Note](https://ibm.box.com/s/wtuzuvk7a0nxbtimo341a8te1sb6w6h0) - for the 'Intro' section of the newly downloaded Sketch file
- Navigate to the visual spec file within this [Patterns Box folder](https://ibm.box.com/s/dfmbd79ek0hmexfz1avg595njmzb2bap) - The image that works successfully for most patterns is the 1312px image.  Adjustments may be needed to have this image accurately reflect the Storybook designs.
- Once complete, save the revised Sketch file in the Layout Pattern folder / sub-folder [here](https://ibm.box.com/s/jao6qplwburqkn1vjrrrvxum1qn3dsoc).
- Export the individual images with a 2X setting, saving them into the Layout Pattern sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing
 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny as a PR Reviewer and Approver.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done.
- [x] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by sethibm** [comment]
Already through a few rounds of comments by Jenny and Lara, on Invision.  Waiting for latest input, before moving into markdown:

https://ibm.invisionapp.com/share/CPO0AUAEK79#/319643584_Pattern_-_Callout_-_With_Media

**Comment by sethibm** [comment]
@wonilsuhibm This one is ready for your review.  Lara and Jenny have inputted already, with various changes made via Invision and Sketch.  

Jacob helped with markdown on this one, as I have not yet learned it. I will try to handle changes you suggest, if any.

https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/565

cc @JennySanchez

**Comment by wonilsuhibm** [comment]
@sethibm Hmmm, i'm getting 404 error. Can you check please?

**Comment by sethibm** [comment]
@wonilsuhibm Oops, it's working now, can check?  

PR:
https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/565
Latest link:
https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/565/index.html

**Comment by wonilsuhibm** [comment]
Thank you for the quick response. Looking good! Let's merge it?
