### ISSUE TITLE
Markdown Publishing - 01 Card Section and 02 Feature Card

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#519]
The content and design can be viewed via #499.

 - Use the design from #499 to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the Layout Pattern assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny as a PR Reviewer and Approver.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Publishing with markdowns is done.
- [x] QA is done.
- [ ] Web page is approved by Linda, Jeff and Wonil
- [ ] Page is published

**Comment by JennySanchez** [comment]
Markdown publishing completed and the PR detail can be viewed [here](https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/527).

**Comment by JennySanchez** [comment]
@ljcarot @jeffchew @wonilsuhibm The page is ready for review. Thank you.

**Comment by wonilsuhibm** [comment]
Hey Jenny, added a PR with some content restructuring: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/549

This PR may have impact on other pages as well. let me know what you think.

**Comment by JennySanchez** [comment]
@wonilsuhibm Thank you for starting the conversation in the PR. Based on the discussion, we will...

- Update the pattern call out treatment. 

We will use Cap and " " when calling out a pattern name in a sentence. 
For example, The ~content block — simple~ "Content block — simple" pattern is typically used for the introductory section on a page.

- Update the "Specification documentation" section to "Design and functional specifications"

**Comment by JennySanchez** [comment]
@wonilsuhibm The page is live and can be viewed [here](https://www.ibm.com/standards/web/ibm-dotcom-library/patterns/feature-card-block). 

We also updated the pattern name to match what we have in the Airtable inventory - FYI.
