### ISSUE TITLE
Content copy and image fixes for the Layout Patterns section

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#558]
### For the Layout Patterns pages published in Sprint 20-15

- [x] Content Group Simple

![Screen Shot 2020-07-27 at 4.38.11 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/4a8e9ca9-de21-4aef-ad17-fb0401334a56) 
![Screen Shot 2020-07-27 at 5.37.19 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/df8f5cad-5420-4976-a3dc-62da5a2f7245)

https://ibm-dotcom-library.mybluemix.net/patterns/content-group-simple

---

- [x] Feature Card Large

![feature-card-block-large-issues.jpg](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/28ce7db8-d288-4e0d-8b9d-3df4923163c2)

---

- [x] Content group pictograms

There's an extra space after the vision and before the "("

![Screen Shot 2020-07-27 at 5.39.37 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/18ca7f76-40bf-4510-874f-faab3c923af8)

---

- [x] Content block simple

![Screen Shot 2020-07-27 at 5.43.09 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/2f057b56-16e6-4107-a1d2-bdb54b0df983)

![Screen Shot 2020-07-27 at 5.43.22 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/d69047c9-0b8c-4093-936e-5de0daee07c9)

---

- [x] Card section with images

![Screen Shot 2020-07-27 at 5.46.07 PM.png](https://images.zenhubusercontent.com/5d96606084daa600013e3afb/833db85e-3425-40d7-a347-1b13db0d9a36)

---

@JennySanchez commented on [Wed Jul 29 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3292#issuecomment-665290973)

- [x] Update the pattern call out treatment. 

We will use Cap and M-dash when calling out a pattern name in a sentence. 

For example, `The content block — simple pattern is typically used for the introductory section on a page.` 

should be 

`The Content block — simple pattern is typically used for the introductory section on a page.`

---

@JennySanchez commented on [Wed Jul 29 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3292#issuecomment-665291672)

- [x] Update the "Specification documentation" section title to "Design and functional specifications"

---

@JennySanchez commented on [Wed Jul 29 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3292#issuecomment-665735815)

- [x] Update the link code to be open the linked page in a separate browser instead of the same browser page.

**View:** https://github.com/carbon-design-system/ibm-dotcom-library-website/wiki/Tips-and-tricks

---

@jacobottesen-dgc commented on [Wed Jul 29 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3292#issuecomment-665783538)

cc. @JennySanchez  

**Updated**  links (open new tab) and Cap/em dash are in the PR:

https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/556

Please review and approve once preview deploy link is ready. Thanks!

**Comment by jacobottesen-dgc** [comment]
cc. @JennySanchez 

PR for adding "Design and functional specifications" heading ready to go:
https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/561

**Comment by JennySanchez** [comment]
- [ ] Update the Logo grid — rich image to fit the 16 columns and avoid too much white space on the left or right-hand side.

![unnamed](https://user-images.githubusercontent.com/45213839/88981889-94af6b00-d28c-11ea-97d5-f2e7871342c3.png)

**Comment by JennySanchez** [comment]
- [ ] Get a decision made on if we need to remove the word "pattern" on the content so we can make group updates for the Layout Pattern section pages.

![Screen Shot 2020-07-31 at 1.58.45 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/9c442a49-5e0c-4d35-b374-b6c691924b7a)

**Comment by JennySanchez** [comment]
- [ ] Overview list links update.

Need to talk to Wonil and LInda.

![Screen Shot 2020-07-31 at 4.31.43 PM.png](https://images.zenhubusercontent.com/5da0db0a9f0a9500014f53bf/0022587f-ad1a-4b36-97f5-58d7363a51ec)

**Comment by JennySanchez** [comment]
- [ ] Update the Callout quote image.

Based on the feedback from Linda in Sprint 20-15 demo, we need to update the reference to not reflect the quote and detail from external resources.

![Screen Shot 2020-08-03 at 11 37 00 AM](https://user-images.githubusercontent.com/45213839/89206256-a93a7e80-d57e-11ea-8b64-49f3cf130927.png)

**Comment by JennySanchez** [comment]
- [ ] Make sure the anchor link set up is consistent across the section.

![Screen Shot 2020-08-03 at 11 47 22 AM](https://user-images.githubusercontent.com/45213839/89206617-25cd5d00-d57f-11ea-97a2-b9886f8ee415.png)
![Screen Shot 2020-08-03 at 11 47 11 AM](https://user-images.githubusercontent.com/45213839/89206619-25cd5d00-d57f-11ea-95df-c9cea68a4d5c.png)
![Screen Shot 2020-08-03 at 11 46 55 AM](https://user-images.githubusercontent.com/45213839/89206620-2665f380-d57f-11ea-9355-65c0198e8729.png)
![Screen Shot 2020-08-03 at 11 46 43 AM](https://user-images.githubusercontent.com/45213839/89206622-26fe8a00-d57f-11ea-8163-a8650805b68f.png)

**Comment by JennySanchez** [comment]
- [ ] Update Lead space page content detail. 
![Screen Shot 2020-08-03 at 2 45 32 PM](https://user-images.githubusercontent.com/45213839/89220922-03940900-d598-11ea-86b7-880604ccf34a.png)

**Comment by JennySanchez** [comment]
- [ ] Move the "Design and functional specifications" section to be above "Development documentation".

**Comment by JennySanchez** [comment]
- [ ] Update and make sure all images are set up at 1312px and exported at 1312 px

**Comment by JennySanchez** [comment]
**Task update:**

All images in Layout Pattern section are updated.
https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/586

**Comment by jacobottesen-dgc** [comment]
Anchor links updated and merged: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/585

**Comment by JennySanchez** [comment]
Yay! We made it.
