### ISSUE TITLE
Content Publishing - Components  (02 Link List)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#573]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the components 

> so that I can utilize the components to my day to day work.

#### Additional information

- Take a look at the [storybook](https://ibmdotcom-react.mybluemix.net/?path=/story/overview-getting-started--page) - so you know how the component works.   You will also use Storybook as a reference to accurately include the images in the Sketch file.
- Download this [Sketch template](https://ibm.box.com/s/qqw0guzaxfezowmm41aoaxhkmeyarblj) to your machine to make the updates. Name the Sketch file with the following convention: Name of the component + version. ex: `Link list v1.0.sketch`
- Use the component description included in the [Components Overview Box Note](https://ibm.box.com/s/kome1qn15bklgydorkymbc3eqz9s0k2z) - for the 'Intro' section of the newly downloaded Sketch file
- For the image creation, please use the components from the Design Kit for image creation, if the component can not be found in the Design Kit, navigate to the visual spec file within this [Component Box folder](https://ibm.box.com/s/vyt75tjqx7mk6g7e8h3vw013zstcdk4s) sometimes it might be under the [Pattern Box folder](https://ibm.box.com/s/dfmbd79ek0hmexfz1avg595njmzb2bap). The image that works successfully for most patterns is the 1312px image. Adjustments may be needed to have this image accurately reflect the Storybook designs. 
- Export the individual images with a 2X setting, saving them into the Components sub-folder that contains the Sketch file.  These exported images will be used when creating the Markdown for publishing. Please use the lowercase with a dash in between for image naming. For example, lightbox-media-viewer.jpg.
- Once complete, save the revised Sketch file in the Components folder / sub-folder [here](https://ibm.box.com/s/pyu51d278bp1nv1kvgpo8zsp53wvx5x3).

 - Use this Sketch file to create the Markdown version of the web page in [Github](https://github.com/carbon-design-system/ibm-dotcom-library-website/tree/master/src/pages/patterns).
    - Find the .mdx file for the component assigned
    - Copy the content from the Sketch file into the .mdx file
    - Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
    - When ready to deploy, include Jenny as a PR Reviewer and Approver.
    - Jenny will review and merge the PR

#### Acceptance criteria
- [x] Content crafting is done.
- [x] Asset image creation is done.
- [x] Page design is done.
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by jacobottesen-dgc** [comment]
@sethibm 

Here is the content for each Link list variations:

**Default**

Default Link list displays links in a card format. Typically used for resource links on the side of the main content of the page.

**Horizontal** 

Horizontal Link List displays links horizontally, icons can be placed on the left or right of text. Typically used within the main content of the page.

**Vertical**

Vertical Link List displays links as a vertical list, icons can be placed on the left or right of text. 

**Vertical with cards**

Vertical with cards Link List combines the Vertical and Default Link lists. Typically used for varying resource links on the side of the main content of the page.

**End of section**

End of section Link List typically used at the end of a section of content to list a number of CTAs for the user.

**Comment by jacobottesen-dgc** [comment]
Content has been added to Markdown. PR can be viewed here: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/604

Seth is updating the images before we merge branch.
