### ISSUE TITLE
Content Publishing - Guidelines (02 IBM.com Style Model overview page MVP version)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#575]
#### User Story

> As an IBM.com Library pattern adopter, 

> I need a way to learn more about the (Name of the Pattern here) pattern 

> so that I can utilize the pattern to my day to day work.

#### Additional information

Based on the IBM.com Style Model page content and IA discussion and work session done in #37, this task is to publish the MVP version of the content agreed on with Wonil.

https://github.com/carbon-design-system/digital-design-ideation/issues/37

#### Acceptance criteria

- [ ] Content crafting is done.
- [ ] Asset image creation is done.
- [ ] Page design is done.
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff and Wonil
- [ ] Web page is published

**Comment by RobertaJHahn** [comment]
@JennySanchez Can I close this issue or should I move it to sprint 20-17?  Let me know.  Thanks.

**Comment by wonilsuhibm** [comment]
The content is here: https://ibm.box.com/s/hno90qbj7x0kkhrla07328naa7sbbd64
And the design/prototype is here: https://ibm.invisionapp.com/share/EJO0GLC65MU#/319702416_IBM-Dot-Com--style-Models--home
And the Sketch file for the design: https://ibm.box.com/s/38d5p6bhz5lq9r73uh9gh8qr2qe7a8wy

**Comment by wonilsuhibm** [comment]
Preview link: https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/650/index.html
PR: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/650

**Comment by wonilsuhibm** [comment]
### Feedbacks
- Case: Style model
- What are the next steps?
- Proper apostrophe
- Contents -> content
- Show numbers in the principles
- Text size and spacing heading size too small
- Contribution should be feedback?
- List intro is weak
- Line spacing in the diagrams
- Main contents -> main content

**Comment by RobertaJHahn** [comment]
@JennySanchez Hi Jenny, It looks like the PR merge is blocked.  Can you take a look at it?  I am moving this issue to the next sprint so that I can close out 20-19.  

cc;  @wonilsuhibm

**Comment by JennySanchez** [comment]
@RobertaJHahn The merge is blocked bc there are two change requests and needs to be reviewed by four reviewers.

@wonilsuhibm can you take a look at the two change requests? Is it intentional to have four reviewers for this PR? If it is, once the updates are done, you might wanna ping all reviewers to review it asap so we can get the content live asap.
