### ISSUE TITLE
Finalize the Components - Overview page description and intro copy

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#577]
@JennySanchez commented on [Mon Aug 03 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/3400)

#### User Story

> As an IBM.com Library components adopter, 

> I need a simple but straight forward paragraph on the Components overview page list and the intro section of each component website page

> so that I can learn about the components before I spend more time learning about the rest of the detail 

#### Additional information

- The current descriptions can be viewed in the **Components - Overview page (Component list for Q3 update)** [BOX document](https://ibm.box.com/s/kome1qn15bklgydorkymbc3eqz9s0k2z). We need to make updates and make sure the content reflects the latest information.
- The website stream will utilize the finalized content for website page publishing.

#### Acceptance criteria

- [ ] Content is updated and finalized
- [ ] Content is ready for the website stream to make updates to the overview page and implement for the Components section content publishing.

**Comment by JennySanchez** [comment]
@oliviaflory FYI on this task issue existed based on our conversation last week.
@wonilsuhibm Thank you in advance for pairing up with Olivia for Components description and individual component intro section copy crafting.

**Comment by JennySanchez** [comment]
@wonilsuhibm @oliviaflory Thank you for getting started on this task. As mention in the Slack conversation, I made additional comments for consideration and they are in green color text. Let me know if you have any questions.

**Comment by RobertaJHahn** [comment]
Olivia will check with Jenny to see whether this issue can be closed or should be moved to sprint 20-17.
