### ISSUE TITLE
Content Publishing - Guidelines (06 RTL language guidelines)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#638]
@jacobottesen-dgc commented on [Mon Apr 27 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2209)

#### User Story

> As a `IBM.com creator`:
> I need to:
understand how to design and develop RTL

> so that I can:
correctly implement RTL pages throughout the IBM.com experience.
#### Acceptance criteria
 - [ ] _{{Finalized RTL content with content strategist}}_
 - [ ] _{{Produce production ready images}}_
 - [ ] _{{Review with RTL language expert}}_

Box note rough draft: https://ibm.box.com/s/oxlh87ivzrlz9x0j2wnm01ztsn0lnzns

---

@RobertaJHahn commented on [Mon Jun 01 2020](https://github.com/carbon-design-system/ibm-dotcom-library/issues/2209#issuecomment-636925268)

Moving to backlog as the RTL expert has to be identified.

**Comment by JennySanchez** [comment]
#### User Story

> As an IBM.com Library components adopter, 

> I need a way to learn more about the IBM.com Library,

> so that I can learn the detail through the guidelines and adopter IBM.com Library to my day to day work properly. 

#### Additional information

**Please contact Wonil and Jenny to find out if the content should be on the Get Started page or Guideline section and as an individual page.**

- Work on the content by following the [publishing process](https://ibm.box.com/s/6oiqsvhxtchi1lfozyuw1soje67unbmj) as much as possible and as needed.
- Create the website design with the Sketch App as needed and the Sketch publishing template can be found on the [BOX folder](https://ibm.box.com/s/ma72t84m75fvd3qqkyz8cm6gfx9b7vou). Once complete, save the revised Sketch file in the Guideline folder / sub-folder [here](https://ibm.box.com/s/40lbqd2bfxwm1qv8k6dy8qwyq48qd6xg).
- Once the content is reviewed (with stakholders or SME of the topic) and finalized. 
- Copy the content from the Sketch file into the .mdx file for the markdown publishing process to start.
- Once complete, create the Pull Request and review, using the Preview link, to be sure it matches the Sketch file design
- When ready to deploy, include Jenny as a PR Reviewer and Approver.
- Jenny will review and merge the PR

#### Acceptance criteria
- [ ] Content crafting is done.
- [ ] Asset image creation is done (if needed)
- [ ] Page design is done (if needed)
- [ ] Publishing with markdowns is done.
- [ ] QA'd by Jenny
- [ ] Web page preview is approved by Linda, Jeff, and Wonil
- [ ] Web page is published

**Comment by jacobottesen-dgc** [comment]
Working on adding image assets and content to website. PR can be viewed here: https://github.com/carbon-design-system/ibm-dotcom-library-website/pull/652

@ Kenny is helping me to figure out to add images side by side to style the page correctly.

**Comment by jacobottesen-dgc** [comment]
Deploy link for RTL guideline content added in markdown. Please take a look:

https://ibmdotcom-library.s3.us-south.cloud-object-storage.appdomain.cloud/deploy-previews/652/index.html

cc. @wonilsuhibm @JennySanchez @ljcarot

**Comment by jacobottesen-dgc** [comment]
Content merged to master branch. Live page can be viewed here: https://www.ibm.com/standards/web/ibm-dotcom-library/guidelines/right-to-left
