### ISSUE TITLE
Create a patterns publishing roadmap for cupcake website

### ISSUE THREAD

**Issue by larahanlon2** [carbon-design-system/ibm-dotcom-library-website#65]
#### User Story

> As a Cupcake website creator

> I need to know what patterns will be published on the cupcake website 

> so that I can: use it for alignment in our team and discussion with the Carbon Team.

#### Task
- Jenny and Lara to work together to figure out what patterns will be published in order of priority.
- Jenny to create a publishing roadmap wiki page

#### Acceptance criteria
- [ ] Roadmap items agreed by Wonil, Lara, Jenny.

**Comment by larahanlon2** [comment]
I've been chatting with Lila and Jill about their time and priorities for documenting their web simplification patterns for the cupcake site. They will try to add stories to their current + upcoming WS sprints to start work on it asap but right now they don't know what they will begin with or when.

Aside from `overview` and `leadspace left-aligned` this publishing roadmap is dependent on their availability. I'm thinking we have to move this to backlog.

**Comment by JennySanchez** [comment]
@lara Got it and yes, let's move this to the backlog.

@RobertaJHahn Can you move this to the backlog for us, please? We will need to set priority once we have more information from Lila and Jill.

**Comment by JennySanchez** [comment]
**Note:** We need to update the [Website content inventory list](https://ibm.box.com/s/xamwwg62xezptdx6ic8y9cg857uawmq4) for the Carbon website once this task is completed.

**Comment by larahanlon2** [comment]
Moving this to backlog again because of other priorities.

**Comment by larahanlon2** [comment]
When revisiting this, refer to [Mural](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1580397317100?sender=larahanlon9022&key=4c666c4b-42a2-4a5a-9545-10e19c7a238d) for prioritization and [Boxnote](https://ibm.ent.box.com/notes/565346710895) for process steps.

Ontology visuals can be viewed [here](https://app.mural.co/invitation/mural/digitaldesignsystemsquadwork2176/1579536578502?sender=wonilsuh19286&key=529b9ee1-7e98-44f0-b390-6114379cefa3) and final names [here](https://airtable.com/tblsnDDtb57UVxHpH/viwL7XPwcIgnb8Y4T?blocks=hide).

**Comment by JennySanchez** [comment]
@larahanlon2 Great planning work and thank you again for going over the process steps document with Jim, Jacob and I earlier today.

I shared my estimate and I think four sprints are pretty safe to set as an expectation margin. We want to publish content sooner than four sprints and will do so if we can, it all depends on how complex the pattern is going to be and how much material we can gather in Sprint 1. 

Let me know what do you think after you have a chance to look at my estimate.

**Comment by JennySanchez** [comment]
Publishing work will be done post April release and this task will be closed.
