### ISSUE TITLE
Update the Layout Patterns/Overview page

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#76]
> As a Cupcake website designer

> I need to: update the Patterns Overview page once the patterns roadmap is finalized 

> so that: our adopters can find the most up to date information about Patterns. 

#### Additional information
Current cupcake Patterns overview page can be viewed [here](https://carbon-for-ibm.netlify.com/patterns).

#### Acceptance criteria
- [x] Content and design published with markdowns.
- [x] Content and design reviewed with Jenny and Wonil.
- [x] Content and design accepted by Wonil and Linda.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez Just finished updating the Patterns Overview page

Live link: https://deploy-preview-111--carbon-for-ibm.netlify.com/patterns

**Comment by JennySanchez** [comment]
@larahanlon2 Do you have high-level descriptions of the Content array, Simple long from, and use cases? We need it for the overview page, Type table (see below). Thank you.

![Screen Shot 2019-12-03 at 12 58 05 PM](https://user-images.githubusercontent.com/45213839/70083645-70eb3680-15d2-11ea-92fd-a6da87a26a38.png)

the layout guideline is coming in Q1 2020

**Comment by JennySanchez** [comment]
Layout overview page updates completed and can be viewed [here](https://carbon-for-ibmdotcom.netlify.com/patterns).

@larahanlon2 @wonilsuhibm Let me know if we missed anything for the v1.0.0 release.

**Comment by jacobottesen-dgc** [comment]
@JennySanchez @larahanlon2 

This is finished based on the content that Lara gave me. I think is it ready for review!

Live Link: https://deploy-preview-188--carbon-for-ibmdotcom.netlify.com/patterns

**Comment by JennySanchez** [comment]
This task is completed. Items need to be fixed are recorded in the dev fix issue #63.
