### ISSUE TITLE
Finalize Carbon website cupcake vision (IA)

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#93]
#### User Story

> As a Cupcake website content creator

> I need to: know where our current Cupcake content for IBM.com is going to live on the Carbon website

> so that I can: make a plan on migration and move forward with a clear vision in mind.

#### Task
- Scott, Wonil, Lara, Olivia, Jacob, and Jenny to meet regularly to align on the IA work Scott, Jan, and Jeannie are working on right now - issue 
- The group will collaborate and assist Scott's IA work by providing feedback based on our understanding of user needs and sharing specific needs from the streams.

#### Acceptance criteria
- [ ] Final IA decision made and accepted by Mike and Elliott.

**Comment by JennySanchez** [comment]
@ScottBokma I'd assume we will put this task to the backlog until Jan can focus on this with us, correct?

**Comment by ScottBokma** [comment]
@JennySanchez Yes, this is on-hold till Jan is assigned back on the IA of Carbon and we are able to get he up to speed at where we are with our IA.

**Comment by JennySanchez** [comment]
Got it. Thank you for confirming @ScottBokma .

@RobertaJHahn Can we have this task issue moved to the Backlog column? Thank you.

**Comment by RobertaJHahn** [comment]
@JennySanchez Priority label removed.  Moved to backlog pipeline.  Sprint assignment removed.  Done.

**Comment by JennySanchez** [comment]
**Task update:** Met with Scott today. Scott will save all related work files to the website BOX folder and a follow-up call for tomorrow morning is scheduled as well for final handoff.

**Comment by RobertaJHahn** [comment]
This task is on hold until January 2020 when the Carbon team can pick up the work.  There is no timeline from Carbon.  Removing this issue from the cupcake v1.0.0 release and moving it to backlog.  @JennySanchez
