### ISSUE TITLE
Cupcake website release announcement/communication planning

### ISSUE THREAD

**Issue by JennySanchez** [carbon-design-system/ibm-dotcom-library-website#97]
> As a Cupcake website content creator,

> I need a way: to let adopters know when and what information is published

> So that: the adopters can consume the information.

#### Task
- Collaborate with Wonil and Linda to aligned on when and how to make the announcement.

#### Acceptance criteria
- [ ] Share the outcome with our team

**Comment by JennySanchez** [comment]
@wonilsuhibm Let's discuss this in our huddle this afternoon as well.

**Comment by JennySanchez** [comment]
Based on the discussion today:
1. Wonil will provide a list of the senior designers by EOD for us to announce the soft launch tomorrow.
2. We will do the website lunch for all DGC designers in January.

**Comment by wonilsuhibm** [comment]
As discussed, let's announce to all DGC design org members through the `dgc-design` channel as a soft launch on Monday, Dec 23rd.

"We would like your feedback" as the main message.

**Comment by JennySanchez** [comment]
@wonilsuhibm Sounds good. What do you think of the message below?

"@channel IBM.com Library team is doing a dark launch with our website. You can tell all the IBMers if you are excited, but it is not available to adopters as of yet. We would love your feedback! I’ve created a box note for our team to gather all the feedback from you around the different components, resources, and overall general content on the website. Our goal is to gather feedback during the first week of January 2020, make modifications, then launch publicly. https://ibm.box.com/s/cuhmld1kb6e1y70pjxqkl1gkhgvdpiaa

Have a super-duper holiday season, y'all!!!"

---
The box note can be viewed [here](https://ibm.box.com/s/cuhmld1kb6e1y70pjxqkl1gkhgvdpiaa) and I have the mailing list of the DGC designers ready to be added on Monday.

![Screen Shot 2019-12-20 at 11 23 28 AM](https://user-images.githubusercontent.com/45213839/71279838-5b3e7680-231f-11ea-982e-99ff2e4f3e48.png)

**Comment by wonilsuhibm** [comment]
Thank you @JennySanchez. Some editing suggestions here:

`@channel IBM.com Library guideline website is now available to DGC designers for preview. This is the beginning of the new design standards website for all IBM.com makers. This website is supplementary to CarbonDesignSystem.com and will cover many essential topics around building IBM.com experiences such as IBM.com library components, grid and color usage on IBM.com, layout patterns, SEO, accessibility, among many.`

`We don't have much at the moment as this is an MVP, but we would love to get your feedback to inform our steps forward. We've created a Box note  to gather feedback from you around the different topics including components, resources, and overall general content on the website. Our goal is to gather feedback during the first week of January 2020, make modifications, then launch publicly. https://ibm.box.com/s/cuhmld1kb6e1y70pjxqkl1gkhgvdpiaa Have a super-duper holiday season, y'all.`

**Comment by JennySanchez** [comment]
@wonilsuhibm Sounds good.
